### ISSUE TITLE
Tests: Re-enable WPT job for GCC CI

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#10]
The logs for this last time it was enabled show that the WebDriver fails to accept the connection from wpt.py when run in the CI configuration. It works locally with ASAN+UBSAN, so there must be a deeper problem here.

**Comment by ChaseKnowlden** [comment]
Can we close this issue?

**Comment by ADKaster** [comment]
This issue is overcome by events. The specific job was removed for clang as well.
