### ISSUE TITLE
WebDriver: Missing endpoints

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#1040]
This is a revival of https://github.com/SerenityOS/serenity/issues/15551, with the already-implemented endpoints stripped out.

---

WebDriver is the API for remote-controlling a browser process, as used by [WebPlatformTests](https://web-platform-tests.org/). It has a lot of different endpoints, so to make it clear which ones are missing, here's a handy list!

To add an endpoint you'll need to modify the code in three places:
- The library definitions at `Userland/Libraries/LibWeb/WebDriver`.
- The WebDriver side at `Userland/Services/WebDriver`.
- The Browser side at `Userland/Services/WebContent/WebDriver`.

Comment here or refer to this issue in your PR to get your endpoints checked off the list. :^)

You can find the same table in the spec at https://w3c.github.io/webdriver/#endpoints

- [x] `POST /session/{session id}/frame` [Switch To Frame](https://w3c.github.io/webdriver/#dfn-switch-to-frame)
#1403
- [x] `POST /session/{session id}/frame/parent` [Switch To Parent Frame](https://w3c.github.io/webdriver/#dfn-switch-to-parent-frame)
#1412
- [x] `POST /session/{session id}/element/{element id}/clear` [Element Clear](https://w3c.github.io/webdriver/#dfn-element-clear)
#1727
- [x] `POST /session/{session id}/element/{element id}/value` [Element Send Keys](https://w3c.github.io/webdriver/#dfn-element-send-keys)
#1725
- [x] `POST /session/{session id}/actions` [Perform Actions](https://w3c.github.io/webdriver/#dfn-perform-actions)
#1566
#1706
- [x] `DELETE /session/{session id}/actions` [Release Actions](https://w3c.github.io/webdriver/#dfn-release-actions)
#1566

Additionally, some endpoints are partially implemented with FIXMEs in `Userland/Services/WebContent/WebDriverConnection.cpp` which need resolving before WebDriver will work completely.

**Comment by hanpham32** [comment]
I can work on implementing the rest of FIXMEs in `Userland/Services/WebContent/WebDriverConnection.cpp`

**Comment by trflynn89** [comment]
All endpoints are implemented.
