### ISSUE TITLE
Ladybird news: are there news?

### ISSUE THREAD

**Issue by rubyFeedback** [LadybirdBrowser/ladybird#1069]
So, I checked, and news appear to be here:

https://ladybird.org/#news

Now compare it to GraalVM news:

https://medium.com/graalvm

I am not saying ladybird should be like GraalVM in regards to news. But, one thing that I think
is currently better in regards to GraalVM is that they write articles, with a date, and also show the
date at once (though they use medium.com, which is a negative, but here I focus just on the content,
not where it is hosted). That way we can look after, say, 8 months (we all may be busy meanwhile) and
look at what is new.

Of course ldaybird is newer and more recentish, so we can not expect the same article series
and blog entries, but I am thinking more long term. If you look at the current articles there,
none of those is time-stamped - at the least not when you look at it on https://ladybird.org/#news.
So I think the first change should be a mandatory timestamp right there, somewhere next to
those articles. That way we can look at things chronologically. The time IS showing up in the
individual article, so this is only a display issue. Hence convenience.

Also, aside from this, I would suggest to the ladybird devs that every once in a while there is
some summary over the development. This does not have to happen every week, not even
ever month, mind you. It does not have to happen regularly as such either. But I think something
that may be managable, would be nice, and just summarizes the main changes. Say, once every
three months, or once every six months, may be a good compromise. That way people can be
updated quite quickly. At any rate, thank you for reading this suggestion; it can be closed once 
one or the other main ladybird dev has a look at it.

**Comment by trflynn89** [comment]
There are monthly newsletters, e.g. https://ladybird.org/newsletter/2024-07-31/

They are not currently accessible from the home page, but there is an open issue on the website repo to do so, and to improve newsletters in general:
https://github.com/LadybirdBrowser/ladybird.org/issues/19
