### ISSUE TITLE
Freezing when scrolling a page on MacOS

### ISSUE THREAD

**Issue by nikpivkin** [LadybirdBrowser/ladybird#1074]
Hi! Some parts of the page freezes while scrolling during and after page loading. 

https://streamable.com/fz2g2c

My machine:
MacOS arm64
Built ladybird using the command:
`CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ ./Meta/ladybird.sh run`

**Comment by AtkinsSJ** [comment]
Hi, that video link has expired. That makes it impossible to reproduce so I'm going to close this issue.

If you still have the problem, you can reopen this or create a new issue. GitHub lets you embed videos by drag and dropping them into the text field, so it might be better to do that in future so the video doesn't disappear again. :^)
