### ISSUE TITLE
Site not loading any more in newest Ladybird

### ISSUE THREAD

**Issue by jogibear9988** [LadybirdBrowser/ladybird#1082]
Hello,

my site https://node-projects.github.io/web-component-designer-demo/index.html did load and show up.

With the new ladybird version from the last 3-4 days it does not work any more. of course, the whole site is not yet working completely (see other issue: https://github.com/LadybirdBrowser/ladybird/issues/53), but normally it loaded.

This are the errors I get:

        6772031.397 WebContent(10013): FIXME: Unimplemented IDL interface: 'HTMLElementPrototype.nonce'
        6772031.398 WebContent(10013): FIXME: run_iframe_load_event_steps called with null nested browsing context
        6772031.508 WebContent(10013): FIXME: Unimplemented Navigator.maxTouchPoints
        6772031.508 WebContent(10013): FIXME: Unimplemented IDL interface: 'HTMLElementPrototype.draggable'
        6772036.809 WebContent(10013): FIXME: Unimplemented IDL interface: 'ClipboardPrototype.readText'
        6772036.809 WebContent(10013): FIXME: Unimplemented Navigator.maxTouchPoints
        6772036.809 WebContent(10013): FIXME: Unimplemented Navigator.maxTouchPoints
        6772037.181 WebContent(10013): FIXME: Unimplemented Navigator.maxTouchPoints
        6772037.393 WebContent(10013): ResourceLoader: Failed load of: "https://node-projects.github.io/favicon.ico", Error: Load failed: 404, Duration: 323ms
        6772037.671 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772037.671 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772037.671 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772037.672 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772037.672 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772037.672 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772037.688 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772037.784 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772037.895 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772038.033 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772038.252 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772038.262 WebContent(10013): Potential FIXME: Creating unknown generic element 'metadata' in namespace 'http://www.w3.org/2000/svg'
        6772038.262 WebContent(10013): Potential FIXME: Creating unknown generic element 'rdf:rdf' in namespace 'http://www.w3.org/2000/svg'
        6772038.262 WebContent(10013): Potential FIXME: Creating unknown generic element 'cc:work' in namespace 'http://www.w3.org/2000/svg'
        6772038.262 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:format' in namespace 'http://www.w3.org/2000/svg'
        6772038.262 WebContent(10013): Potential FIXME: Creating unknown generic element 'dc:type' in namespace 'http://www.w3.org/2000/svg'
        6772038.263 WebContent(10013): Potential FIXME: Creating unknown generic element 'sodipodi:namedview' in namespace 'http://www.w3.org/2000/svg'
        6772038.891 WebContent(10013): Unhandled JavaScript exception (in promise): [SyntaxError] Invalid or ambiguous export entry 'RegularGraphRows'
        6772038.891 WebContent(10013):     at <unknown>
            at <unknown>

**Comment by AtkinsSJ** [comment]
There's some issue with the HTTP requests:

```
VERIFICATION FAILED: !is_error() at /home/sam/Projects/ladybird/AK/Error.h:180
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x7b714d6d3eaf]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-http.so.0 HTTP::Job::on_socket_connected() 0x289) [0x7b714dc6deb9]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0(+0x3668f) [0x7b714db2f68f]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0(+0x3668f) [0x7b714db2f68f]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::ThreadEventQueue::process() 0x18e) [0x7b714db4555e]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoopImplementationUnix::exec() 0x2c) [0x7b714db2875c]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-core.so.0 Core::EventLoop::exec() 0x37) [0x7b714db272c7]
/home/sam/Projects/ladybird/Build/ladybird/libexec/RequestServer(+0x3c6c3) [0x5af2675576c3]
/home/sam/Projects/ladybird/Build/ladybird/libexec/RequestServer(+0x3c49b) [0x5af26755749b]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-threading.so.0(+0x6375) [0x7b714db5f375]
/home/sam/Projects/ladybird/Build/ladybird/libexec/../lib/liblagom-threading.so.0(+0x61ca) [0x7b714db5f1ca]
/lib/x86_64-linux-gnu/libc.so.6(+0x9ca94) [0x7b714d09ca94]
/lib/x86_64-linux-gnu/libc.so.6(+0x129c3c) [0x7b714d129c3c]
 54189 Lost connection to RequestServer
 54151 Lost connection to RequestServer
```

**Comment by jogibear9988** [comment]
this is fixed, was cause of a new library
