### ISSUE TITLE
WebContent is able to crash without the GUI noticing

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#1137]
As found in #861. Sometimes the `WebContent` process can crash, but remain as a zombie process, without the GUI process noticing that anything is wrong. No "page crashed!" message is shown, the page just stops responding at all to interaction.

Here's a screenshot of my system monitor after this has happened. The upper `WebContent` process has died in this way. The lower one is running normally.

![image](https://github.com/user-attachments/assets/a9437a7d-ccb9-41f9-ba40-c9ad61f8513a)

It seems like this isn't consistent across computers. For reference, I'm on `Kubuntu 22.04.4 LTS x86_64`.

**Comment by jamierocks** [comment]
I've observed this behaviour too, on a few occasions. I run Fedora 40.

**Comment by AtkinsSJ** [comment]
From discussing it on Discord, it's possible this only *doesn't* happen when running in WSL.

**Comment by shannonbooth** [comment]
Oh, sorry for not being clear, I am seeing the issue currently on WSL, but I wasn't for #861 at an earlier stage (also on WSL). My setup has changed (some behavioural differences I have noticed) but I don't know what the difference is at this stage

**Comment by AtkinsSJ** [comment]
Haven't checked it yet, but this change is suspicious:

https://github.com/LadybirdBrowser/ladybird/commit/4cc3d598f96560c02369a22973b0f75c9f1607a7#diff-e3dc0f3e9f6bf6b6d6a1e306d09eef939288786dbb74070af7745b4112cab18aR39

**Comment by tcl3** [comment]
Bisected to: 5f8d852d, using http://wpt.live/css/css-images/empty-radial-gradient-crash.html as a test page.

CC: @trflynn89
