### ISSUE TITLE
Getting and putting ImageData on a canvas swaps Red and Blue channels

### ISSUE THREAD

**Issue by circl-lastname** [LadybirdBrowser/ladybird#120]
```html
<script>
let area = document.createElement("canvas");
let areaCtx = area.getContext("2d");

area.width = 32;
area.height = 32;
  
areaCtx.fillStyle = "#ffffff";
areaCtx.fillRect(0, 0, 32, 32);

{
  let imageData = areaCtx.getImageData(0, 0, area.width, area.height);

  imageData.data[0] = 255;
  imageData.data[1] = 0;
  imageData.data[2] = 0;

  areaCtx.putImageData(imageData, 0, 0);
}

{
  let imageData = areaCtx.getImageData(0, 0, area.width, area.height);

  if (imageData.data[0] == 255) {
    console.log("PASS");
  } else {
    console.log("FAIL");
  }
}
</script>
```
The above minimal code reproduces this behavior, also can be seen on https://circl-lastname.github.io/Pixedit/

**Comment by circl-lastname** [comment]
Bisected to 59cb7994c676a79c70c3b37c93b424d58b591769

**Comment by awesomekling** [comment]
> Bisected to [59cb799](https://github.com/LadybirdBrowser/ladybird/commit/59cb7994c676a79c70c3b37c93b424d58b591769), I believe it's a bitmap type mismatch between the canvas and imageData

:facepalm: :facepalm: :facepalm: 

You're totally right. The best fix here is to revert this and add a test proving that we now do things right, so we avoid regressing it in the future :)

**Comment by circl-lastname** [comment]
Done in #166
