### ISSUE TITLE
Google's upcoming JPEG-XL decoder

### ISSUE THREAD

**Issue by RubenKelevra** [LadybirdBrowser/ladybird#1280]
Google is sponsoring the development of an JPEG-XL decoder written in Rust, to reduce the attack surface - which is planned to be added to Firefox.

I was wondering if this is also an option for Ladybird to use?

Just want to open the discussion here about it.

Reference: https://github.com/mozilla/standards-positions/pull/1064

**Comment by LucasChollet** [comment]
Not need to discuss that now, the decoder doesn't exist yet.
But if this new decoder ends up having strong technical advantages over `libjxl`, then sure, why not adopt it.

**Comment by RubenKelevra** [comment]
Hey @LucasChollet,

thanks for the feedback!

I understand the current stance on the JPEG-XL decoder, and it makes sense not to rush into discussions until the Rust version matures. However, given the potential for security improvements and Rust's growing role in modern browser development, I believe it could bring significant value in the long term.

I'll keep an eye on its progress and performance benchmarks, and I'd be happy to revisit the topic once more details emerge.

**Comment by LucasChollet** [comment]
Don't get me wrong, I do think that it has a lot of potential. But as the project is (at least, as of today) to develop something for Firefox. Adopting it before Firefox doesn't make a lot of sense IMO.

So don't expect any change over here before that happens.

**Comment by AtkinsSJ** [comment]
I'm going to close this as there's nothing we can current do. When that library is ready we can investigate it. :+1:

**Comment by RubenKelevra** [comment]
@AtkinsSJ I mean there's already a different decoder pretty far in the works. Maybe worth a look?

https://github.com/tirr-c/jxl-oxide
