### ISSUE TITLE
Suggestion, for another interface

### ISSUE THREAD

**Issue by FrostKnight** [LadybirdBrowser/ladybird#1285]
There is a toolkit, called FLTK, 

https://www.fltk.org/

It is still being worked on even now.

I didn't know whether I should ask now or after you get closer to a stable release.

Anywho though, I was suggesting having this be an alternate way to install ladybird whenever its finished, not the only way.

Supposedly, it is very low bloat when it comes to resources used.

Even if is not a good time now, I hope you will ponder this. Let me know though, I am curious if it could be an option later on or ever.

I do suspect you would put it on hold if you considered it though. You still haven't released a stable after all.

Anywho, GL with your web browser.

**Comment by ADKaster** [comment]
At this time a third-party fork or downstream that maintains their own chrome (browser UI process) that uses the FLTK toolkit would be more in line with our goals.

We would of course be available to ping for help and suggestions on integration. I don't think it makes sense to start such a port until we get closer to release.

**Comment by FrostKnight** [comment]
> At this time a third-party fork or downstream that maintains their own chrome (browser UI process) that uses the FLTK toolkit would be more in line with our goals.
> 
> We would of course be available to ping for help and suggestions on integration. I don't think it makes sense to start such a port until we get closer to release.

That's fair, but I appreciate you considering such a thing at all.

Yeah, your probably right, it probably makes sense to wait till its done. I didn't know if it was posisble to work on ahead of time to make it easy to switch between the two ideals or w/e.

But it seems there is no hurry currently. Well good to know anyhow.
