### ISSUE TITLE
Background color not drawn beneath nested inline elements

### ISSUE THREAD

**Issue by Gingeh** [LadybirdBrowser/ladybird#1286]
```html
<span style="background: blue; color: red">
    one <span>two</span> three
</span>
```
![image](https://github.com/user-attachments/assets/f95489d2-c7b8-4244-aff2-55448a3896f8)
(minimized from https://ismy.blue/)

**Comment by Gingeh** [comment]
This behaviour has changed after #1829.
Before: 
![before](https://github.com/user-attachments/assets/0a0aad20-c029-49e1-bf61-1f2d61f7a257)
After: 
![after](https://github.com/user-attachments/assets/cdbb1cdc-2716-4d96-b3e8-f907d15820ae)

I believe this code is relevant:
https://github.com/LadybirdBrowser/ladybird/blob/421cf8d9bf276cff61acdc32dc55d978d37fb671/Userland/Libraries/LibWeb/Layout/LayoutState.cpp#L381-L387
Nested inline children are not counted as fragments so they're skipped when calculating the `PaintableWithLines` content width.

**Comment by AtkinsSJ** [comment]
Ping @kalenikaliaksandr: this sounds related to what you worked on recently.
