### ISSUE TITLE
No error page is shown when attempting to navigate to a `file://` that does not exist

### ISSUE THREAD

**Issue by dlarocque** [LadybirdBrowser/ladybird#1322]
When trying to navigate to a `file://` URL that does not exist, we don't get redirected to an error page. When trying to visit a `http://` URL that does not exist, we get redirected to `Base/res/ladybird/templates/error.html`.

**Comment by dlarocque** [comment]
Nevermind. This was an issue on my end- this works fine.

**Comment by circl-lastname** [comment]
There is supposed to be. Can you verify you're running a recent version of Ladybird?

**Comment by AtkinsSJ** [comment]
Yeah I'm trying it now and getting the error page.
![image](https://github.com/user-attachments/assets/fee70a58-4c2a-4997-9c57-e93e1bb47a96)

Is it failing for a particular path? And as circl asked, how up to date is your Ladybird version?

**Comment by dlarocque** [comment]
My fork was out of date. Sorry I made you guys look into this- my bad!
