### ISSUE TITLE
PPA or openSUSE Build Service

### ISSUE THREAD

**Issue by luigifab** [LadybirdBrowser/ladybird#1332]
I know that ladybird is pre alpha, but could you think to create some repositories for nightly build?

[PPA](https://launchpad.net/~luigifab/+archive/ubuntu/packages) : for Ubuntu, Debian... any distributions based on APT/DEB packages

[openSUSE build service](https://build.opensuse.org/) : for openSUSE, Fedora, Mageia, Debian, Ubuntu, Arch...

_Remember the epoch of Compiz with his daily updates for Ubuntu!_

**Comment by trflynn89** [comment]
We are not focused on package distribution at this time.
