### ISSUE TITLE
Please rename LibWeb back to LibHTML

### ISSUE THREAD

**Issue by sjehuda** [LadybirdBrowser/ladybird#1347]
I write this now, before this projects becomes even more popular.

This is not a technical matter, yet I deffinitely think you should read this.

### Web

Why web and why internet?

Web is of spider (web) and, by the way, net is of fish (net).

Both, are entraping.

Did you hear of the DARPA and Pentagon  project "Life log"?

Another project, allegedly by the "private sector" was started at the same day that the project "Life log" was announced (just announced) as closed.

This is an HTML browser, not a web browser. Web is not a proper word.

### Blog

What is the word Blog?

To me, blog was always a stupid word, ever since I was a kid.

Why not journal or a diary, eh?

Why not "personal publication" (like personal computer) etc.?

Actually, "Live Journal" is a services which does just the same as WordPress, and it uses the word journal.

Again, what is blog?

B + log.

Be + log.

Be = am, are, is.

You be log = You are log

He be log = He is log.

Log = journal.

We are people. We are human. We are not rehistries, not are we papers.

### WWW

World Wide Web

Why world and why web?

Why wide word instead of (just) word?

WWW = ווו = 666 (Hebrew letter Vav).

All these are not by mistakes.

### Words

Words have power, and when we repeat words and putting them into context, we further influence ourselves by the words that we use.

I am not fond of the hypes that occur every time with stranger and stranger jargons every year.

I suggest to give it a thought, and be as much as literal as possible.

### Conclusion

We are browsing HTML files on top of a telecommunication system.

The more we use net, web, log etc. we bound to actualize these terms upon ourselves.

Cheers!

**Comment by circl-lastname** [comment]
It's called LibWeb because it does HTML, CSS, and SVG I'm pretty sure, not just HTML

**Comment by sjehuda** [comment]
Because CSS and ECMA (i.e. JS) were originally designed for HTML, then
I suppose LibHTML should be fine.

And I think that HTML is the best appropriate, because of the arguments
I have raised earlier.

Also, EPUB and CHM files also include CSS and JS, and supported
libraries are called LibEPUB and LibCHM.
