### ISSUE TITLE
Rename "cross-origin opener policy" to "opener policy"

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#1387]
As changed here: https://github.com/whatwg/html/pull/10579

As well as renaming our [`CrossOriginOpenerPolicy`](https://github.com/LadybirdBrowser/ladybird/blob/master/Userland/Libraries/LibWeb/HTML/CrossOrigin/CrossOriginOpenerPolicy.h), we'll need to update any spec comments that refer to it. That'll involve a lot of looking through the [changes](https://github.com/whatwg/html/pull/10579/files) in that PR, finding where we implement that part of the spec, and changing the text.

**Comment by 0xkon1** [comment]
Is this issue still up for grabs?

**Comment by AtkinsSJ** [comment]
Sure! Go ahead. :^)

**Comment by 0xkon1** [comment]
I hope this was what is asked for. Almost forgot to change the comments tho. I looked at the links too, but seems like they haven't been updated and the old links point to the current spec.
