### ISSUE TITLE
Request: Test Suite (specifically for .html pages) as well as "milestones"

### ISSUE THREAD

**Issue by rubyFeedback** [LadybirdBrowser/ladybird#1394]
So ladybird is still young and fresh - and most likely incomplete as of right now.

This is also officially stated on the main README:

"Ladybird is in a pre-alpha state, and only suitable for use by developers"

Ok that's fair enough. We can not expect ladybird to be ready within a few months
and support every possible modern/current web-centric specification, I get that.

Still, there are people who may ask ... "is it ready yet ... is it ready yet ... is it ..."

And then the devs may say "no ... it'll take some more decades I mean it'll take
some more time". Ok, but that is also a bit tiresome, so ... rather than say "it
is ready when it is ready", what if ladybird would actually refer to a specification?

What I mean with that is not just boring technical documentants, but:

a) visually appealing "show where we are at", and
b) a practical way to find out what is supported via ladybird already

For b), specifically, I would mean common websites. Such as youtube. But, of
course, if that is too far on the horizon, really simple websites, where individual
capabilities are showcased - the CSS support, the support for HTML tags, and
so forth. A bit like the mozilla documentation, but more meant as a practical
"milestone" variant and less so for an explanation what this or that does.

**Ideally this could also be a working-ref, a working-specification, so that people
could follow the development of ladybird every once in a while**.

For instance, the ScummVM project, trying to make old games playable, also has
a website that lists support for games.

For instance here:

https://www.scummvm.org/compatibility/

That may not be the most elegant one, but I like the idea of using colour charts to indicate
what works, and how well that works. Perhaps ladybird could also have such a specification.

Ideally this could be a website, and it could list which HTML tags are supported, which CSS
rules are supported - and, most importantly, how the compatibility of common websites
goes. I am not saying you have to check for ALL websites, but, say, list some websites that
are important (youtube, google, wikipedia, and some more) and then indicate how well the
page works (can be simple, e. g. a category of four entries per website).

The idea here is also for users and testers to try things out and to see what needs to be done
next (at the least in this regard). And it also gives people who regularly check on ladybird some
means to see or feel what kind of progress has been made.

I am not saying this should be updated daily or so, but, say, like every end of the week this can
be automatically stored by some script (ideally actually testable in a "headless" variant of 
ladybird, so not just a browser for people but an API set that people could use, so it could
also be used for a scripting approach).

Anyway. This is mostly an idea. As you guys probably don't want to have issues open that 
are more related to an idea, rather than e. g. a bug report, I'll close it to help keep the
issue tracker clean(er).

**Comment by ADKaster** [comment]
We have a big end goal date. Mid-2026 for early adopters alpha. Plus later milestones. 

Soon :tm: we'll put together issues for each of our "target sites" for the alpha listing the highest priority missing features
