### ISSUE TITLE
LibWeb/SVG: Missing icons on NeoGAF.com

### ISSUE THREAD

**Issue by konrad1977** [LadybirdBrowser/ladybird#141]
Version: 2f5cf8ac204a58dc2a6f722dd95015c6c2fb7a78
link: https://www.neogaf.com/forums/gaming-discussion.2/

<img width="1728" alt="Skärmavbild 2024-06-12 kl  07 50 07" src="https://github.com/LadybirdBrowser/ladybird/assets/4384932/ad1aa31b-792f-44a8-843c-3db059b5dd9b">

**Comment by awesomekling** [comment]
Looks like they are inline SVGs that pull from an external SVG via `<use>`:

```html
<div class="structItem-iconContainer">
    <svg class="icon icon-orb" role="img">
	    <use xlink:href="/styles/neogaf/defs.svg#icon-orb"></use>
    </svg>
</div>
```
