### ISSUE TITLE
Unable to run ladybird.sh in ubuntu

### ISSUE THREAD

**Issue by Melyns** [LadybirdBrowser/ladybird#1456]
Followed the docs. First error is 

`die: Do not run ladybird.sh as root, your Build directory will become root-owned`

fixed that by creating a fake user... then when i run the script again  `sudo -u username ./ladybird.sh build`
```
fatal: detected dubious ownership in repository at '/content/ladybird'
To add an exception for this directory, call: git config --global --add safe.directory /content/ladybird
```

**Comment by AtkinsSJ** [comment]
Hi. That message was telling you not to use `sudo`, because it breaks things. Why were you using it? Did you have problems without it?

**Comment by Melyns** [comment]
Yes. Initially I simply couldn't run it without sudo. I also tried the recommended parameters `git config --global --add safe.directory /content/ladybird` but that didn't seem to do anything...

**Comment by skyrising** [comment]
Did you run the initial `git clone` as root? If so, try again with a fresh clone using a regular user.

**Comment by circl-lastname** [comment]
Yeah as per skyrising, try deleting the current clone and making a new one in your user directory as the user

**Comment by Melyns** [comment]
that didnt work, the script insisted that im using root privilege despite me not using sudo anywhere in the process. I have no clue how serious is the build directory being root-owned, nor how this software works, but i suggest adding a graceful way to handle root privilege thing. "WARNING: You are trying to run the script as a root, <reason why this is a bad idea>. Type YES to proceed." now if this is stupid recommendation that causes lot of issue then i understand, just forget what i said. 

what fixed my issue is removing these lines from `buildvcpkg.sh` and `ladybird.sh.` The browser compiled and ran without issues. thanks for you time.

```
if [ "$ci" -eq 0 ]; then
    exit_if_running_as_root "Do not run BuildVcpkg.sh as root, parts of your Toolchain directory will become root-owned"
fi
```

`exit_if_running_as_root "Do not run ladybird.sh as root, your Build directory will become root-owned"`

**Comment by circl-lastname** [comment]
The build directory should not be root-owned. Be aware that your current setup is unsupported
