### ISSUE TITLE
x.com shows browser unsupported screen

### ISSUE THREAD

**Issue by ChaseKnowlden** [LadybirdBrowser/ladybird#1476]
I'm trying to go to smallcappicks (my dad's old twitter account), and it displays this browser is no longer supported.

**Comment by awesomekling** [comment]
You need to spoof another user-agent string. Any of chrome, Firefox or Safari should work. It’s dumb but they require it :/

**Comment by ChaseKnowlden** [comment]
Fixed with UA spoof.
