### ISSUE TITLE
LibJS: Implement `HostLoadImportedModule()` to spec

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#1549]
We seem to have two implementations of this:
- https://github.com/LadybirdBrowser/ladybird/blob/8d6f36f8d6c0aea0253df8c84746f8c99bf79b4d/Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp#L413 which conforms to a previous version of the spec, but is now outdated; and
- https://github.com/LadybirdBrowser/ladybird/blob/8d6f36f8d6c0aea0253df8c84746f8c99bf79b4d/Userland/Libraries/LibJS/Runtime/VM.cpp#L574 which is ad-hoc

As well as updating them, it would be good to combine them if possible.

Related, step 9 in `JavaScriptModuleScript::create()` is gone from the current spec, and instead forms part of the `HostLoadImportedModule()` algorithm, so that will need changing at the same time.

**Comment by Arhcout** [comment]
I was able to update `s_main_thread_vm->host_load_imported_module` but I don't know how to combine the fucnction,
any idea?
