### ISSUE TITLE
Crash on cnbc.com

### ISSUE THREAD

**Issue by ChaseKnowlden** [LadybirdBrowser/ladybird#1577]
Crashes when starting to scroll the page.

VERIFICATION FAILED: !width.might_be_saturated() at /Users/chase/dev/ladybird/Userland/Libraries/LibWeb/Layout/LayoutState.cpp:573
0   liblagom-ak.0.0.0.dylib             0x0000000104e9c884 ak_verification_failed + 216
1   liblagom-web.0.0.0.dylib            0x0000000106ca1710 Web::Layout::LayoutState::UsedValues::set_content_height(Web::CSSPixels) + 0
2   liblagom-web.0.0.0.dylib            0x0000000106c661d8 Web::Layout::BlockFormattingContext::layout_block_level_children(Web::Layout::BlockContainer const&, Web::Layout::AvailableSpace const&) + 448
3   liblagom-web.0.0.0.dylib            0x0000000106c65910 Web::Layout::BlockFormattingContext::run(Web::Layout::AvailableSpace const&) + 116
4   liblagom-web.0.0.0.dylib            0x0000000106c7b7f8 Web::Layout::FormattingContext::calculate_max_content_width(Web::Layout::Box const&) const + 400
5   liblagom-web.0.0.0.dylib            0x0000000106c71b18 Web::Layout::FlexFormattingContext::determine_flex_base_size_and_hypothetical_main_size(Web::Layout::FlexFormattingContext::FlexItem&) + 1416
6   liblagom-web.0.0.0.dylib            0x0000000106c7057c Web::Layout::FlexFormattingContext::run(Web::Layout::AvailableSpace const&) + 180
7   liblagom-web.0.0.0.dylib            0x0000000106c7b7f8 Web::Layout::FormattingContext::calculate_max_content_width(Web::Layout::Box const&) const + 400
8   liblagom-web.0.0.0.dylib            0x0000000106c83d58 Web::Layout::FormattingContext::compute_width_for_absolutely_positioned_non_replaced_element(Web::Layout::Box const&, Web::Layout::AvailableSpace const&)::$_0::operator()(Web::CSS::Length const&) const + 1620
9   liblagom-web.0.0.0.dylib            0x0000000106c7f8ec Web::Layout::FormattingContext::compute_width_for_absolutely_positioned_non_replaced_element(Web::Layout::Box const&, Web::Layout::AvailableSpace const&) + 564
10  liblagom-web.0.0.0.dylib            0x0000000106c7e884 Web::Layout::FormattingContext::compute_width_for_absolutely_positioned_element(Web::Layout::Box const&, Web::Layout::AvailableSpace const&) + 228
11  liblagom-web.0.0.0.dylib            0x0000000106c85428 Web::Layout::FormattingContext::layout_absolutely_positioned_element(Web::Layout::Box const&, Web::Layout::AvailableSpace const&) + 328
12  liblagom-web.0.0.0.dylib            0x0000000106c666c8 Web::Layout::BlockFormattingContext::parent_context_did_dimension_child_root_box() + 452
13  liblagom-web.0.0.0.dylib            0x0000000106c856b4 Web::Layout::FormattingContext::layout_absolutely_positioned_element(Web::Layout::Box const&, Web::Layout::AvailableSpace const&) + 980
14  liblagom-web.0.0.0.dylib            0x0000000106c666c8 Web::Layout::BlockFormattingContext::parent_context_did_dimension_child_root_box() + 452
15  liblagom-web.0.0.0.dylib            0x0000000106c656cc Web::Layout::BlockFormattingContext::~BlockFormattingContext() + 44
16  liblagom-web.0.0.0.dylib            0x0000000106a41dac Web::DOM::Document::update_layout() + 496
17  liblagom-web.0.0.0.dylib            0x0000000106b53c8c Web::HTML::HTMLElement::offset_width() const + 44
18  liblagom-web.0.0.0.dylib            0x0000000107047cb4 Web::Bindings::HTMLElementPrototype::offset_width_getter(JS::VM&) + 100
19  liblagom-js.0.0.0.dylib             0x000000010532eed8 AK::Function<JS::ThrowCompletionOr<void> (JS::Declaration const&)>::operator()(JS::Declaration const&) const + 80
20  liblagom-js.0.0.0.dylib             0x00000001054dd074 JS::NativeFunction::internal_call(JS::Value, AK::Span<JS::Value const>) + 400
21  liblagom-js.0.0.0.dylib             0x00000001054e5b2c JS::Object::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*, JS::Object::PropertyLookupPhase) const + 536
22  liblagom-js.0.0.0.dylib             0x00000001054e5ae0 JS::Object::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*, JS::Object::PropertyLookupPhase) const + 460
23  liblagom-js.0.0.0.dylib             0x00000001054e5ae0 JS::Object::internal_get(JS::PropertyKey const&, JS::Value, JS::CacheablePropertyMetadata*, JS::Object::PropertyLookupPhase) const + 460
24  liblagom-js.0.0.0.dylib             0x0000000105397ecc JS::ThrowCompletionOr<JS::Value> JS::Bytecode::get_by_id<(JS::Bytecode::GetByIdMode)0>(JS::VM&, AK::Optional<JS::Bytecode::IdentifierTableIndex>, JS::Bytecode::IdentifierTableIndex, JS::Value, JS::Value, JS::Bytecode::PropertyLookupCache&, JS::Bytecode::Executable const&) + 340
25  liblagom-js.0.0.0.dylib             0x0000000105379604 JS::Bytecode::Interpreter::run_bytecode(unsigned long) + 15788
26  liblagom-js.0.0.0.dylib             0x0000000105375518 JS::Bytecode::Interpreter::run_executable(JS::Bytecode::Executable&, AK::Optional<unsigned long>, JS::Value) + 412
27  liblagom-js.0.0.0.dylib             0x0000000105466698 JS::ECMAScriptFunctionObject::ordinary_call_evaluate_body() + 432
28  liblagom-js.0.0.0.dylib             0x0000000105465f78 JS::ECMAScriptFunctionObject::internal_call(JS::Value, AK::Span<JS::Value const>) + 448
29  liblagom-web.0.0.0.dylib            0x0000000106da1c3c Web::WebIDL::invoke_callback(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, JS::MarkedVector<JS::Value, 0ul>) + 256
30  liblagom-web.0.0.0.dylib            0x0000000106919248 JS::Completion Web::WebIDL::invoke_callback<JS::NonnullGCPtr<JS::Array>&, Web::IntersectionObserver::IntersectionObserver*>(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, JS::NonnullGCPtr<JS::Array>&, Web::IntersectionObserver::IntersectionObserver*&&) + 512
31  liblagom-web.0.0.0.dylib            0x0000000106918ed0 AK::Function<void ()>::CallableWrapper<Web::Bindings::queue_mutation_observer_microtask(Web::DOM::Document const&)::$_0>::call() + 848
32  liblagom-web.0.0.0.dylib            0x00000001068f1a18 AK::Function<void (Web::CSS::CSSRule const&)>::operator()(Web::CSS::CSSRule const&) const + 76
33  liblagom-web.0.0.0.dylib            0x0000000106b34a00 Web::HTML::EventLoop::perform_a_microtask_checkpoint() + 52
34  liblagom-web.0.0.0.dylib            0x0000000106da1cb0 Web::WebIDL::invoke_callback(Web::WebIDL::CallbackType&, AK::Optional<JS::Value>, JS::MarkedVector<JS::Value, 0ul>) + 372
35  liblagom-web.0.0.0.dylib            0x0000000106c52138 AK::Function<void ()>::CallableWrapper<Web::HTML::WindowOrWorkerGlobalScopeMixin::run_timer_initialization_steps(AK::Variant<JS::NonnullGCPtr<Web::WebIDL::CallbackType>, AK::String>, int, JS::MarkedVector<JS::Value, 0ul>, Web::HTML::WindowOrWorkerGlobalScopeMixin::Repeat, AK::Optional<int>)::$_0>::call() + 364
36  liblagom-web.0.0.0.dylib            0x00000001068f1a18 AK::Function<void (Web::CSS::CSSRule const&)>::operator()(Web::CSS::CSSRule const&) const + 76
37  liblagom-web.0.0.0.dylib            0x00000001068f1a18 AK::Function<void (Web::CSS::CSSRule const&)>::operator()(Web::CSS::CSSRule const&) const + 76
38  liblagom-web.0.0.0.dylib            0x0000000106b34cc8 Web::HTML::EventLoop::process() + 148
39  liblagom-web.0.0.0.dylib            0x0000000106d27088 AK::Function<void ()>::CallableWrapper<Web::Platform::TimerSerenity::TimerSerenity()::$_0>::call() + 88
40  liblagom-core.0.0.0.dylib           0x0000000104d93df4 AK::Function<void ()>::operator()() const + 76
41  liblagom-core.0.0.0.dylib           0x0000000104d98ebc Core::EventReceiver::dispatch_event(Core::Event&, Core::EventReceiver*) + 112
42  liblagom-core.0.0.0.dylib           0x0000000104dad218 Core::ThreadEventQueue::process() + 452
43  liblagom-core.0.0.0.dylib           0x0000000104d92d18 Core::EventLoopImplementationUnix::exec() + 44
44  liblagom-core.0.0.0.dylib           0x0000000104d91568 Core::EventLoop::exec() + 72
45  WebContent                          0x00000001046a9094 serenity_main(Main::Arguments) + 3880
46  WebContent                          0x0000000104736a90 main + 216
47  dyld                                0x000000018fa58274 start + 2840

**Comment by jamierocks** [comment]
Same issue as GH-1236, just height is affected rather than width.
