### ISSUE TITLE
`scrolller.com` not loading at all

### ISSUE THREAD

**Issue by circl-lastname** [LadybirdBrowser/ladybird#1578]
Ladybird @ ec15f8fa626e5b0faf5b3e420080e944ab31ff11 on Linux Qt

Attempting to open `https://scrolller.com/` leads to no result, no log messages, and no error page. Attempting to refresh returns the URL bar to it's previous content. Navigating using the URL bar or anchor on a different page results in the same page remaining loaded,

**Comment by chaseWillden** [comment]
Even on chrome, I don't see any results for this site:

https://scrolller.com/

**Comment by shlyakpavel** [comment]
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/b908d0f3-60dd-45fe-afd0-e3fb19ec2fcd">
As of b22341fc772b538f725f2657c2e3af39cb1af143 , it's fine on my machine. Could you please recheck on yours?

**Comment by circl-lastname** [comment]
Yeah it works now
