### ISSUE TITLE
Couldn't sign in to YouTube

### ISSUE THREAD

**Issue by ChaseKnowlden** [LadybirdBrowser/ladybird#1607]
<img width="1912" alt="Screenshot 2024-10-02 at 4 32 29 PM" src="https://github.com/user-attachments/assets/ddb7ba8a-3607-4303-9530-f0715714a366">

I can't even get YouTube Premium to work.

**Comment by circl-lastname** [comment]
In order to log into Google, spoof your User Agent as Chrome/Firefox
YouTube itself won't work yet however. This is a known issue (see #1495)

**Comment by ChaseKnowlden** [comment]
Thanks!

**Comment by ChaseKnowlden** [comment]
Duplicate of #928
