### ISSUE TITLE
gentoo package in sft overlay

### ISSUE THREAD

**Issue by TheJJ** [LadybirdBrowser/ladybird#167]
i've packaged the current git version (tested 991759f453349baf754ec3aa22934fae66377ab2) for gentoo:

 https://github.com/SFTtech/gentoo-overlay/tree/master/www-client/ladybird

this is in the **sft** gentoo overlay.

maybe worth noting somewhere in the documentation :)

**Comment by TheJJ** [comment]
on a side note: to avoid build-time downloads, i mirror the versions of icu, public suffix list and timezone db in the ebuild.

maybe this can be improved by allowing to use the system's icu, timezone info and a (to be done) package of the public suffix list.

**Comment by circl-lastname** [comment]
If you feel it is worthy to include, you may make a PR doing so, keep in mind that other 3rd party packages of Ladybird (such as the AUR one) are also not mentioned in the documentation

**Comment by ADKaster** [comment]
Thanks for packaging the application!

We won't accept a PR to add your package to official documentation, however. Ladybird is in a pre-alpha state, as stated in the README. If we allow non-developer users to get easy access to the application in its current state, we'll miss our opportunity to make a good first impression. Currently, large parts of the web platform are not implemented in LibWeb, and the GUI frontends we have are largely just developer-focused UIs to allow us to test the web engine underneath.

When we have an actual product that we're happy showing to end users, we'll make an announcement.

**Comment by TheJJ** [comment]
i used the same reasoning for a long time in [openage](https://github.com/SFTtech/openage), but realized it's more important to have easy dev-setups and early visibility - people will accept, follow the project and figure out that things are still in the making (and even more want to get their hands dirty to influence the project, if they're able to and few things are set in stone already).

the gentoo-9999 version makes it clear it's the git version and not any release :)

nevertheless, i'm really curious how Ladybird will evolve, good luck and
happy hacking :smile_cat:
