### ISSUE TITLE
Application crash on macOS

### ISSUE THREAD

**Issue by konrad1977** [LadybirdBrowser/ladybird#172]
git sha: 5e2ee4447e41b9d194e034a32d4fc928118be6f1

[callstack.txt](https://github.com/user-attachments/files/15846162/callstack.txt)
[terminal_output.txt](https://github.com/user-attachments/files/15846163/terminal_output.txt)

**Comment by kalenikaliaksandr** [comment]
I checked attached stack trace and it seems to be request server crash. I don't think we can fix or verify if problem is gone unless you provide a reduction or steps to reproduce the crash.
