### ISSUE TITLE
Incorrect dimensions of a `<div>` with `display:table`

### ISSUE THREAD

**Issue by stasoid** [LadybirdBrowser/ladybird#1726]
This html is displayed incorrectly:
```html
<!doctype html>
<div style="width:30px; height:30px; border:10px solid black; display:table;">
```
Reduced from `Tests/LibWeb/WPT/wpt/css/CSS2/abspos/abspos-containing-block-initial-004c.xht`

**Comment by AtkinsSJ** [comment]
Hi, thanks for the report and the reduction!

Does #1542 help at all?

**Comment by stasoid** [comment]
@AtkinsSJ Nope, same.
