### ISSUE TITLE
Middle click handler not executed in the Qt version

### ISSUE THREAD

**Issue by diath** [LadybirdBrowser/ladybird#175]
When using Ladybird Qt on Linux, clicking on links using the middle mouse button does nothing, furthermore, setting breakpoint on `tab->view().on_link_middle_click` in `BrowserWindow` reveals that the callback from the `WebContentView` doesn't fire at all.

**Comment by hughdavenport** [comment]
I've been meaning of pulling over https://github.com/LadybirdBrowser/ancient-history/pull/139 to do just this as I find it frustrating that it just acts as a left click
