### ISSUE TITLE
Android: Add replacement for ffmpeg

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#1886]
We should be able to use one of two solutions for implementing Video and Audio playback:

- MediaPlayer: https://developer.android.com/media/platform/mediaplayer
- Jetpack Media3: https://developer.android.com/media/media3

If there are other solutions for our media playback use case, such as how we're using Oboe instead of the default Android audio manager, we should look at those as well.

**Comment by Olekoop** [comment]
Isn't this a duplcate of #421?

**Comment by ADKaster** [comment]
Ah, should have done a search.
