### ISSUE TITLE
[Social Media] More, but shorter, videos about Ladybird (I'll close this issue request, to avoid having too many open issues here)

### ISSUE THREAD

**Issue by rubyFeedback** [LadybirdBrowser/ladybird#2092]
Hey there folks,

This is just a small comment in regards to videos about ladybird.

I, and probably others, are interested in the news about ladybird, e. g. "is it ready yet?".

One way to keep up to date is via videos, such as:

https://www.youtube.com/watch?v=0aXSBCtELZ4

The video is fine, but as I have the attention span of a squirrel on a sugar nut rush, a length of 17 to 19 minutes is too long, IMO. I'd like to see more a range of, say, 4-8 minutes or so - just the primary gist, and showcasing a little bit of what is new. Ideally without too much audio, e. g. more eye candy than spoken text, though spoken text is also fine. For me I just want slightly shorter videos.

Anyway, that is the gist of it. Kind of a request to have more smaller videos about ladybird. This can be about singular features too, by the way, e. g. "this website now works, let me show you its features".

Thanks for reading!

**Comment by trflynn89** [comment]
You've opened and immediately closed several issues like this. The issue tracker is for technical issues, please refrain from opening these
