### ISSUE TITLE
Unicode and color rendering.

### ISSUE THREAD

**Issue by konrad1977** [LadybirdBrowser/ladybird#215]
site: [https://www.barometern.se/](https://www.barometern.se/)

✓ Man slog sönder rutor i bilaffär ✓ Polis kände misstänkt lukt
This is the text, but it just displays empty squares (Typical font issue)

This offer is hard to resist in Ladybird (because its missing the close button)
<img width="1432" alt="Skärmavbild 2024-06-19 kl  16 17 26" src="https://github.com/LadybirdBrowser/ladybird/assets/4384932/3346a0e0-1a13-4016-8608-34daba3ec49f">

Another really strange issue, the colors are different in Ladybird compared to Safari:
<img width="360" alt="Skärmavbild 2024-06-19 kl  16 21 39" src="https://github.com/LadybirdBrowser/ladybird/assets/4384932/1be49a62-e967-44d1-a9b4-ca873fa83062">

**Comment by Gingeh** [comment]
This issue appears to have been resolved:
![Screenshot from 2024-09-06 07-48-22](https://github.com/user-attachments/assets/742417e1-9e57-4270-bf0f-f524665751d8)
![Screenshot from 2024-09-06 07-22-23](https://github.com/user-attachments/assets/bd9e8abd-2314-476f-bb32-ed4fec443185)

**Comment by AtkinsSJ** [comment]
Yup, I can't reproduce the issues either. Thanks for the report!
