### ISSUE TITLE
Android builds seem to be broken

### ISSUE THREAD

**Issue by Olekoop** [LadybirdBrowser/ladybird#220]
I am trying to build a Android build of Ladybird, however after dealing with external libraries and having the program compiled all I get is a white screen with URL bar.
![Screenshot_20240619-224706_Ladybird](https://github.com/LadybirdBrowser/ladybird/assets/154007291/6db3cccf-d83e-4ea4-bc91-dea72d15df0a)

I have tried to find a culprit and I found that commit 6836091a215229a6fdd44559bd22b5dce7345f66 and commits after cause this issue. Commits before that result in a working build.

## Funding

- We're using [Polar.sh](https://polar.sh/SerenityOS) to allow folks to offer a reward for completing this issue.
- The contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/LadybirdBrowser/ladybird/issues/220">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/LadybirdBrowser/ladybird/issues/220/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/LadybirdBrowser/ladybird/issues/220/pledge.svg">
</picture>
</a>

**Comment by awesomekling** [comment]
Thank you @thatoddmailbox for contributing to close this issue! ⭐

The rewards from this issue, totaling $100, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
