### ISSUE TITLE
Invite Mozilla to ladybird officially.

### ISSUE THREAD

**Issue by rubyFeedback** [LadybirdBrowser/ladybird#2200]
I'll close this issue request, as I am only half-serious and half-joking; plus it is not a good "technical" issue, of course. Nonetheless I think there may be a tiny bit of merit in this.

Recently the Mozilla Foundation did what it is doing since about a decade or so: fires people.

See this recent article:

https://techcrunch.com/2024/11/05/mozilla-foundation-lays-off-30-staff-drops-advocacy-division/

So with the Mozilla Foundation doing what Google demands of it, I think it is time to invite the Mozilla devs, both current and former, to join ladybird. Now, of course any hobbyist and freelancer can do so anyway, so I understand that some devs need financial contributions and support, which is not so trivial to change quickly, so I have no solution for that part. Nonetheless I think ladybird should CONSIDER this here in the long run. Sooner or later ladybird will work better than firefox for most use cases (I am pretty certain that will come, as firefox has almost zero momentum, whereas ladybird has a lot more momentum right now) and there may be some strategic benefit in regards to the code base when there are more developers. I mean just reading what Nabiha Syed writes, already translates to "Firefox is now officially dead" in my opinion.

**Comment by AtkinsSJ** [comment]
Please stop opening issues and immediately closing them. You've been asked [before](https://github.com/LadybirdBrowser/ladybird/issues/2092#issuecomment-2452255589).

If an issue is worth discussing, leave it open. If it's not, don't open it.
