### ISSUE TITLE
textarea overflows when "border-radius:1rem"

### ISSUE THREAD

**Issue by named-dodo** [LadybirdBrowser/ladybird#2271]
### Summary

When i scroll down a page past a textarea, it's contents breaks out and spills over downwards.
This seems to happen exactly when the textarea leaves my screen.

### Operating system

Linux

### Steps to reproduce

1. Use reduced example
2. Scroll down.
3. See text overflow

### Expected behavior

Text shouldn't escape it's textarea

### Actual behavior

Text escapes and draws over the remaining content.

### URL for a reduced test case

https://www.useragents.me/

### HTML/SVG/etc. source for a reduced test case

```html
<!DOCTYPE html>
<html>
<body>
<textarea style="border-radius:1rem;">
01) Lorem impsum.
02) Lorem impsum.
03) Lorem impsum.
04) Lorem impsum.
05) Lorem impsum.
06) Lorem impsum.
07) Lorem impsum.
08) Lorem impsum.
09) Lorem impsum.
10) Lorem impsum.
</textarea>
<p style="margin-top:5000px;">bottom</p>
</body>
</html>
```

### Log output and (if possible) backtrace

```shell
dodo@dodo:~/ladybird/ladybird$ ./Meta/ladybird.sh run
ninja: Entering directory `/home/dodo/ladybird/ladybird/Build/ladybird'
[0/2] Re-checking globbed directories...
ninja: no work to do.
QStandardPaths: wrong permissions on runtime directory /run/user/1000/, 0755 instead of 0700
Ladybird PID file '/run/user/1000/Ladybird.pid' exists with PID 676, but process cannot be found
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

### Screenshots or screen recordings

![image](https://github.com/user-attachments/assets/9e267106-fc12-4f1c-b178-5156bd05dd3a)
![image](https://github.com/user-attachments/assets/5725d22b-da89-4408-9e57-4c06ffde6370)

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by AtkinsSJ** [comment]
At a guess, it sounds like we're skipping the masking operation when the mask is outside the viewport?

**Comment by AtkinsSJ** [comment]
Playing around with this, it's not specific to `<textarea>`, but applies to any situation where:
- Parent element has border radius and scrollable overflow
- Child element has `overflow: visible` which is the default
eg, this modified test case shows the same issue:
```html
<!DOCTYPE html>
<html>
<body>
<div style="border: 1px solid black; border-radius:1rem; height: 50px; overflow: auto;">
<div>
01) Lorem impsum.<br/>
02) Lorem impsum.<br/>
03) Lorem impsum.<br/>
04) Lorem impsum.<br/>
05) Lorem impsum.<br/>
06) Lorem impsum.<br/>
07) Lorem impsum.<br/>
08) Lorem impsum.<br/>
09) Lorem impsum.<br/>
10) Lorem impsum.<br/>
</div>
</div>
<p style="margin-top:5000px;">bottom</p>
</body>
</html>
```

Also, removing the `continue` here fixes the issue:
https://github.com/LadybirdBrowser/ladybird/blob/93712b24bf298a61d3a614ce57574739015776c2/Libraries/LibWeb/Painting/DisplayList.cpp#L61-L64

I'll see if I can fix this properly.
