### ISSUE TITLE
LibRegex/Optimizer: Loop to atomic group rewriter causes regex to not match with escaped brackets around capture group

### ISSUE THREAD

**Issue by Lubrsi** [LadybirdBrowser/ladybird#2296]
```js
"__computeMeta(type, key, value)".match(/([^\s]+?)\(([\s\S]*)\)/)
```

Expected: `[ "__computeMeta(type, key, value)", "__computeMeta", "type, key, value" ]`
Actual: `null`

Removing the call to `attempt_rewrite_loops_as_atomic_groups` in RegexOptimizer fixes this.
Removing the escaped `\(` and `\)` will cause it to match.
Reduced from YouTube's JS.

**Comment by alimpfard** [comment]
:sob:

**Comment by alimpfard** [comment]
Further reduction: `"x)".match(/[\S]*\)/)` (expected: `[ "x)" ]`, as of master: `null`)
