### ISSUE TITLE
Dependency issue in CMake causing build failure

### ISSUE THREAD

**Issue by shannonbooth** [LadybirdBrowser/ladybird#2359]
There is a dependency issue which could potentially cause a build failure, see on master: https://github.com/LadybirdBrowser/ladybird/actions/runs/11857444468/job/33045830292#step:11:472

Appears to be caused by https://github.com/LadybirdBrowser/ladybird/pull/2346

Relevant comment by Andrew:
> The generation of the bindings for any IDL files that rely on the generated idl file need a dependency added. GenerateWindowOrWorkerInterfaces also needs a dependency on that generated file, since it includes all idl files from idl_files.cmake including ones that require the generated idl.

**Comment by ADKaster** [comment]
Should be fixed by #2360, going to wait for any smoke before closing

**Comment by shannonbooth** [comment]
I think it seems good, CI seems a lot more happy
