### ISSUE TITLE
why c++?

### ISSUE THREAD

**Issue by evrensen467** [LadybirdBrowser/ladybird#244]
hi, can I ask why the devs chose c++ for making this browser when there is rust, zig, go, swift, etc.. which are memory safe and reliable according to modern standards, the government also seems to have declared c++ deprecated and unsafe https://www.whitehouse.gov/wp-content/uploads/2024/02/Final-ONCD-Technical-Report.pdf . I'm just genuinely curious, I'm a novice trying to explore and learn.

**Comment by awesomekling** [comment]
Please do not spam this issue tracker with non-issues.

**Comment by evrensen467** [comment]
im very sorry @awesomekling , where is more appropriate please for me to discuss or ask this?

**Comment by ADKaster** [comment]
If you're truly curious, come chat in the discord, in the #off-topic channel(s). The short answer is: the project began five years ago, and the developers are extremely familiar with C++.

**Comment by evrensen467** [comment]
hi thanks for responding, could you send the discord invite link?

**Comment by ADKaster** [comment]
https://github.com/LadybirdBrowser/ladybird?tab=readme-ov-file#get-in-touch-and-participate

**Comment by sang-shelton** [comment]
> i'm sorry @awesomekling is there a more appropriate place for me to discuss / ask this?

i just heard about this project and also felt a sock when i saw the usage of the buggy C++, but i figured out that the project may have been old and you confirmed it. Thanks for your efforts anyways.
