### ISSUE TITLE
LibWeb/IDL: overload resolution problem

### ISSUE THREAD

**Issue by FMMazur** [LadybirdBrowser/ladybird#2508]
### Summary

issue occur on: [Channel_postMessage_clone_port_error.any.html](https://wpt.live/webmessaging/Channel_postMessage_clone_port_error.any.html)

When passing an array to postMessage function of a MessagePort, it always points to StructuredSerializeOptions interface instead of the sequence method overload:
```idl
  undefined postMessage(any message, sequence<object> transfer);
  undefined postMessage(any message, optional StructuredSerializeOptions options = {}); // <-- points to this
```

While checking the prototype discovered that it wills always point to the overload related to the dictionary_types, but if we add the sequence "type" to the dictionary it will always resolve to the first one that appears on the dictionary.

### Operating system

macOS

### Steps to reproduce

1. Enter the test Channel_postMessage_clone_port_error.any.html
2. wait test to be concluded

### Expected behavior

Result to be Pass

### Actual behavior

Result is Fail

### URL for a reduced test case

https://codepen.io/fmmazur/pen/bGXXYxO

### HTML/SVG/etc. source for a reduced test case

```html
N/A
```

### Log output and (if possible) backtrace

```shell
N/A
```

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by shannonbooth** [comment]
Hmm, I thought I had fixed this issue not long ago, but I guess not, and not enough tests to cover it properly! Will take a look

**Comment by shannonbooth** [comment]
Found the issue, there is an additional overload step which we need to implement. The issue is sequence support in general in overload resolution.
