### ISSUE TITLE
Move New Tab button in tab bar

### ISSUE THREAD

**Issue by sohzm** [LadybirdBrowser/ladybird#252]
The "New Tab" button is positioned in the toolbar, unlike Firefox and Chrome, where it's integrated directly into the tab bar. 

I've attached screenshots for comparison:

![Screenshot from 2024-06-23 04-14-07](https://github.com/LadybirdBrowser/ladybird/assets/68921363/c5423ae7-a1bc-48a9-8add-7664b7b325f9)

![Screenshot from 2024-06-23 04-23-36](https://github.com/LadybirdBrowser/ladybird/assets/68921363/0f27ee8c-660b-44be-96e8-4ad35f55bb3e)

I propose moving the "New Tab" button to the tab bar.

I'm ready to work on this adjustment if the team (or someone) agrees it's a worthwhile update.

**Comment by lukewarlow** [comment]
Interestingly I think Ladybird's layout is the same Gnome web browser (WebKit for Linux), and Safari. So it's not completely an odd one out.

**Comment by trflynn89** [comment]
Yeah, I wanted to put that button in the tab bar when I originally added it, but wasn't able to get it to look nice, so I put it next to the URL bar. See:
https://discord.com/channels/830522505605283862/830525031720943627/1225570437665259625

**Comment by unworld11** [comment]
can this issue be assigned to me?

**Comment by proJM-Coding** [comment]
I would prefer a one line setup like I have with firefox.

![image](https://github.com/LadybirdBrowser/ladybird/assets/81658610/c5906c72-d5ed-4fc0-8e3b-32d4482f5f41)

It saves space and looks modern.

**Comment by GeneralChauhan** [comment]
> https://discord.com/channels/830522505605283862/830525031720943627/1225570437665259625

I cannot open this for some reason, can you copy the image?

I will pick this up and check it.

**Comment by sohzm** [comment]
@GeneralChauhan join SerenityOS discord server to view it: https://discord.com/invite/serenityos

**Comment by GeneralChauhan** [comment]
Got it. Thanks 🙏

**Comment by theonlyasdk** [comment]
> I would prefer a one line setup like I have with firefox.
> 
> ![image](https://private-user-images.githubusercontent.com/81658610/345799257-c5906c72-d5ed-4fc0-8e3b-32d4482f5f41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzI1MjYsIm5iZiI6MTcyMDM3MjIyNiwicGF0aCI6Ii84MTY1ODYxMC8zNDU3OTkyNTctYzU5MDZjNzItZDVlZC00ZmMwLThlM2ItMzJkNDQ4MmY1ZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYzI4OTg3ODQzNTBlNWE0NTI4MjEzOGU2Y2IwN2ZkMzk4NGRiZDA3ZDBlNzNmZWExOGVkMTczMmQ1MWY1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHuzBh6FIICl628tN_Lilpj61l2qPSIU7Y8EqfcR3Ac)
> 
> It saves space and looks modern.

What about people who are on low resolution/small screens?

**Comment by theonlyasdk** [comment]
> The "New Tab" button is positioned in the toolbar, unlike Firefox and Chrome, where it's integrated directly into the tab bar.
> 
> I've attached screenshots for comparison:
> 
> ![Screenshot from 2024-06-23 04-14-07](https://private-user-images.githubusercontent.com/68921363/342001767-c5423ae7-a1bc-48a9-8add-7664b7b325f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzI2MTksIm5iZiI6MTcyMDM3MjMxOSwicGF0aCI6Ii82ODkyMTM2My8zNDIwMDE3NjctYzU0MjNhZTctYTFiYy00OGE5LThhZGQtNzY2NGI3YjMyNWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZjA5ZjQ0YWYyZWNlMWViMjYyYTFlZTMxMjg2ZWYzZjZiODdlOWM5NGYyNjVlNjk4NTE4OTRjYmJhYTE3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PdJKkxwkquJv5S_qd0MZPGau6miWMGGKwSorn3FFBto)
> 
> ![Screenshot from 2024-06-23 04-23-36](https://private-user-images.githubusercontent.com/68921363/342001792-0f27ee8c-660b-44be-96e8-4ad35f55bb3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzI2MTksIm5iZiI6MTcyMDM3MjMxOSwicGF0aCI6Ii82ODkyMTM2My8zNDIwMDE3OTItMGYyN2VlOGMtNjYwYi00NGJlLTk2ZTgtNGFkMzVmNTViYjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MzlhNGI0ZjFjYzI4OGQwMTgxYjYzMDUwYjQ5ZmM0N2Q5ODRlYmEyMDAxODRjYTlmZDVkYjExYmYxZjUyZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ske0EKGjR9iw6s6JEjJpHnF49M1FxCog4PzcWnHLQoo)
> 
> I propose moving the "New Tab" button to the tab bar.
> 
> I'm ready to work on this adjustment if the team (or someone) agrees it's a worthwhile update.

Yes, something like this would be nice especially when its location is configurable just like the hamburger menu

**Comment by proJM-Coding** [comment]
> > I would prefer a one line setup like I have with firefox.
> > ![image](https://private-user-images.githubusercontent.com/81658610/345799257-c5906c72-d5ed-4fc0-8e3b-32d4482f5f41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzI1MjYsIm5iZiI6MTcyMDM3MjIyNiwicGF0aCI6Ii84MTY1ODYxMC8zNDU3OTkyNTctYzU5MDZjNzItZDVlZC00ZmMwLThlM2ItMzJkNDQ4MmY1ZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYzI4OTg3ODQzNTBlNWE0NTI4MjEzOGU2Y2IwN2ZkMzk4NGRiZDA3ZDBlNzNmZWExOGVkMTczMmQ1MWY1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MHuzBh6FIICl628tN_Lilpj61l2qPSIU7Y8EqfcR3Ac)
> > It saves space and looks modern.
> 
> What about people who are on low resolution/small screens?

That is a bit of a problem actually, I didn't think of that. When the window is small though it goes back to normal. 

![image](https://github.com/LadybirdBrowser/ladybird/assets/81658610/5d4f6db2-f70a-4b42-bb09-fd00bc506594)

Here is the github for it if interested: [https://github.com/crambaud/waterfall](https://github.com/crambaud/waterfall)

**Comment by AtkinsSJ** [comment]
Resolved by #629
