### ISSUE TITLE
Unable to focus/type in search box on StackOverflow

### ISSUE THREAD

**Issue by rmg-x** [LadybirdBrowser/ladybird#2530]
I'm unable to use the search box on StackOverflow. I believe it's something to do with our inline-block display mechanism.

Minimal reproduction:
```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <input type="text" />
    <div style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 42px, 0px);">
      <div>
        <span>[tag]</span>
        <span>search within a tag</span>
      </div>
      <div>
        <span>user:1234</span>
        <span>search by author</span>
      </div>
    </div>
  </body>
</html>
```

**Comment by Psychpsyo** [comment]
Further reduction:
```html
<!DOCTYPE html>
<input type="text" />
<div style="position: absolute; transform: translate(0px, 42px);">
  <div>
    This is in the way of the input.
  </div>
</div>
```
It looks like the hit testing isn't aware of the transform.

**Comment by yyny** [comment]
The problematic line is: [`if (fragment_absolute_rect.contains(position_adjusted_by_scroll_offset)) {`](
https://github.com/LadybirdBrowser/ladybird/blob/442629064bd91cd5fe119b344dce4b21a89f4ede/Libraries/LibWeb/Painting/PaintableBox.cpp#L949C1-L949C83).

`fragment_absolute_rect` does not have transformations applied.
