### ISSUE TITLE
Grid layout issue on firefox.com

### ISSUE THREAD

**Issue by awesomekling** [LadybirdBrowser/ladybird#255]
This doesn't look right:
![Screenshot from 2024-06-23 10-40-28](https://github.com/LadybirdBrowser/ladybird/assets/5954907/c2ecfeda-293d-49fd-a89a-eea5e0576c9b)

Simplified reduction:
```html
<!doctype html><style>
    * {
        outline: 1px solid black;
    }
    html {
        background: white;
        position: absolute;
        width: 0;
    }
    body {
        background: orange;
        position: absolute;
    }
    main {
        background: cyan;
        display: grid;
        grid-template-columns: 1fr;
    }
</style><body><main><div>hello
```

**Comment by yogirajbshinde21** [comment]
To fix this, we need to ensure to have proper positioning and structure of elements. 
Can I send a PR to resolve this issue? @awesomekling

**Comment by awesomekling** [comment]
> To fix this, we need to ensure to have proper positioning and structure of elements. Can I send a PR to resolve this issue? @awesomekling

Of course, if you have a fix, please submit it along with a layout test :)

**Comment by kalenikaliaksandr** [comment]
Reduction is rendered correctly on a build from master branch
