### ISSUE TITLE
Suggesting Discussions Tab for opinion and new ideas

### ISSUE THREAD

**Issue by hazho** [LadybirdBrowser/ladybird#256]
Hey awesome people;
I am really glad that I discovered this amazing project, just now..!

but I saw some of the implementations that I found need to be discussed for, before going further in development, hence remembered that it would be best not create an issue for each of those discussable topics and concerns I have, but we discuss and see where things will be directing us, I also would love to contribute in the development as much as it is possible.

looking forward to discuss.. cheers 🥂

**Comment by AtkinsSJ** [comment]
Hi there!

We use Discord to discuss development. [Here's the link.](https://discord.gg/nvfjVJ4Svh)

**Comment by nsartor** [comment]
Are there any plans to use something non-proprietary, such Matrix or Mastodon? 
Thanks!

**Comment by ADKaster** [comment]
No plans to do project discussion anywhere other than our discord server. It meets our needs and is straightforward to moderate.

**Comment by nsartor** [comment]
Thanks for the response.
