### ISSUE TITLE
Build failure | Arch Linux (Aur, yay)

### ISSUE THREAD

**Issue by 6r1d** [LadybirdBrowser/ladybird#2632]
I've tried to install Ladybird in Arch Linux (Aur) using `yay`.
Build fails on two separate, recently updated machines.

*I am not sure whether it's relevant at this point in time, but if the Aur package has more requirements or can't build, maybe it should be edited to change something or indicate an issue.*

Context: `Linux Airhead 6.12.1-arch1-1 #1` `SMP PREEMPT_DYNAMIC` `Fri, 29 Nov 2024 16:04:27 +0000` `x86_64` `GNU/Linux`

**Steps to reproduce**:

1. Run `yay ladybird`
2. Pick either option.
3. The results will probably match my gists: https://gist.github.com/6r1d/98a751592b124bfc9cde8e8d7e2b21a5

**Comment by shlyakpavel** [comment]
https://github.com/user-attachments/assets/0cc4733d-3b5d-4e54-ae40-e38355c73d1e

**Comment by shlyakpavel** [comment]
I don't think we support aur or any other packaging here at the moment. Ladybird is still in early pre-alpha stage, and intended to be built and used by developers

**Comment by 6r1d** [comment]
> I don't think we support aur or any other packaging here at the moment. Ladybird is still in early pre-alpha stage, and intended to be built and used by developers

Well, thanks for answering in a form of text. I don't know who added the Aur package, but thought it may be useful to test.

**Comment by AtkinsSJ** [comment]
Looks like that AUR build is from October 6th, which is more recent than I expected, but still old in Ladybird terms. 😅 But yeah that's a third-party thing, you'd need to fix the aur package if you wanted to use it.
