### ISSUE TITLE
Text/input/wpt-import/css/cssom/serialize-values.html times out in CI

### ISSUE THREAD

**Issue by trflynn89** [LadybirdBrowser/ladybird#2659]
This test takes 2s to run on my desktop in a release build - on CI, especially with GCC sanitizers, it's consistently timing out.

Disabled in #2656

CC @AtkinsSJ

**Comment by AtkinsSJ** [comment]
Hmm. It's probably a good candidate for optimising because it does one thing repeatedly.

One option otherwise would be to mark some tests (slower, more exhaustive ones like this) as disabled on sanitizer builds. But then you lose the benefits of sanitisers. :-/
