### ISSUE TITLE
LibWeb: Move away from usages of Gfx::DeprecatedPainter

### ISSUE THREAD

**Issue by circl-lastname** [LadybirdBrowser/ladybird#269]
DeprecatedPainter, the old Serenity-era CPU-based renderer, was replaced by a new Skia backed Painter. There are some minor uses of DeprecatedPainter mostly outside of LibWeb.

LibWeb usage, where the new Painter should be used instead:
- [x] CanvasRenderingContext2D [here](https://github.com/LadybirdBrowser/ladybird/blob/2f3128333dcd5a781f35272800631d6cf03803ad/Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h#L101) (#1024)
- [X] PaintableBox [here](https://github.com/LadybirdBrowser/ladybird/blob/2f3128333dcd5a781f35272800631d6cf03803ad/Userland/Libraries/LibWeb/Painting/PaintableBox.cpp#L946) (#1143)

Non LibWeb usage, where I'm unsure if the new Painter should be used:
- [x] Qt TVGIconEngine [here](https://github.com/LadybirdBrowser/ladybird/blob/2f3128333dcd5a781f35272800631d6cf03803ad/Ladybird/Qt/TVGIconEngine.cpp#L36) (#2512)
- [x] Android WebViewImplementationNative [here](https://github.com/LadybirdBrowser/ladybird/blob/2f3128333dcd5a781f35272800631d6cf03803ad/Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp#L73) (#2570)

**Comment by doctortheemh** [comment]
Does it make sense to directly implement `CanvasRenderContext2D` directly with Skia?

**Comment by circl-lastname** [comment]
That would potentially lock in the implementation to Skia only meaning extra effort if the project were to switch one day

**Comment by shlyakpavel** [comment]
Can we consider this done?

**Comment by circl-lastname** [comment]
Yes
