### ISSUE TITLE
ffmpeg doesn't build in more secure linux.

### ISSUE THREAD

**Issue by tomFlowee** [LadybirdBrowser/ladybird#2716]
### Summary

When I build ladybird from sources in a jail, one of the security measures is that /tmp is mounted (on a tmpfs) to not allow files there to be executed.

The ffmpeg dependency as built by ladybird doesn't build in that situation.
Now, if I take the git master of ffmpeg and run configure, I instantly get this issue. **Which I don't see in ladybird**.

```
./configure 
Unable to create and execute files in /tmp.  Set the TMPDIR environment
variable to another directory and make sure that it is not mounted noexec.
Sanity test failed.
```

So, issue 1:
while ffmpeg configure fails fast, ladybird doesn't.

Issue 2:
no clue why ffmpeg decided on breaking the simple security premise of using noexec on /tmp, but ladybird doesn't need to care if they just set TMPDIR to the build dir (or some subdir) for this specific project-build and isolate the weirdness there.

ps. as configure of ffmpeg instantly reports the long message, I strongly suspect that reporting a bug there is not going to result in a change in behavior there. They made their choice, it seems to me.

### Operating system

Linux

### Steps to reproduce

not releveant input field.

### Expected behavior

not releveant input field.

### Actual behavior

not releveant input field.

### URL for a reduced test case

not releveant input field.

### HTML/SVG/etc. source for a reduced test case

```html
not releveant input field.
```

### Log output and (if possible) backtrace

```shell
not releveant input field.
```

### Contribute a patch?

- [ ] I’ll contribute a patch for this myself.

**Comment by shlyakpavel** [comment]
Are we talking about vcpkg-provided ffmpeg here?

**Comment by tomFlowee** [comment]
yes.

Here is the log

```
Installing 82/114 ffmpeg[avcodec,avdevice,avfilter,avformat,core,dav1d,openh264,opus,swresample,swscale,theora,vorbis,vpx,webp,zlib]:x64-linux@6.1.1#11...
Building ffmpeg[avcodec,avdevice,avfilter,avformat,core,dav1d,openh264,opus,swresample,swscale,theora,vorbis,vpx,webp,zlib]:x64-linux@6.1.1#11...
/home/zander/ladybird/Meta/CMake/vcpkg/release-triplets/x64-linux.cmake: info: loaded overlay triplet from here
/home/zander/ladybird/Build/vcpkg/buildtrees/versioning_/versions/ffmpeg/15b90b33b76e69c2d9b876b32c4c9b47c97846ed: info: installing overlay port from here
-- Using cached ffmpeg-ffmpeg-n6.1.1.tar.gz.
-- Cleaning sources at /home/zander/ladybird/Build/vcpkg/buildtrees/ffmpeg/src/n6.1.1-95b141da41.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/zander/ladybird/Build/vcpkg/downloads/ffmpeg-ffmpeg-n6.1.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0002-fix-msvc-link.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-dependencies.patch
-- Applying patch 0005-fix-nasm.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0020-fix-aarch64-libswscale.patch
-- Applying patch 0040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch
-- Applying patch 0041-add-const-for-opengl-definition.patch
-- Applying patch 0042-fix-arm64-linux.patch
-- Using source at /home/zander/ladybird/Build/vcpkg/buildtrees/ffmpeg/src/n6.1.1-95b141da41.clean
-- Found external ninja('1.12.1').
-- Getting CMake variables for x64-linux
-- Building Options: --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --disable-autodetect --target-os=linux --enable-pthreads --cc=cc --cxx=c++ --nm=nm --ar='ar' --ranlib=ranlib --strip=strip --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --disable-postproc --enable-swresample --enable-swscale --disable-alsa --disable-amf --disable-libaom --disable-libass --disable-avisynth --disable-bzlib --enable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --enable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --disable-openssl --enable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --disable-libx264 --disable-libx265 --disable-libxml2 --enable-zlib --disable-libsrt --disable-libmfx --enable-cross-compile --disable-static --enable-shared --pkg-config=/bin/pkg-config
-- Building Release Options: --enable-optimizations --extra-ldflags=-L"/home/zander/ladybird/Build/release/vcpkg_installed/x64-linux/lib"
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/bash ./build.sh
    Working Directory: /home/zander/ladybird/Build/vcpkg/buildtrees/ffmpeg/x64-linux-rel
    Error code: 1
    See logs for more information:
      /home/zander/ladybird/Build/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-config.log
      /home/zander/ladybird/Build/vcpkg/buildtrees/ffmpeg/build-x64-linux-rel-out.log

Call Stack (most recent call first):
  buildtrees/versioning_/versions/ffmpeg/15b90b33b76e69c2d9b876b32c4c9b47c97846ed/portfile.cmake:726 (vcpkg_execute_required_process)
  scripts/ports.cmake:196 (include)


error: building ffmpeg:x64-linux failed with: BUILD_FAILED
```

**Comment by ADKaster** [comment]
I suspect this is a vcpkg issue at the root. If you go to an empty directory and run `vcpkg install ffmpeg` does it have the same behavior? If so, it should be reported upstream to vcpkg.

Does setting TMPDIR in your environment fix this issue? 

If not, does setting it in Meta/CMake/vcpkg/generate_vcpkg_toolchain_variables.cmake fix the issue? That script generates another CMake script to inject env vars into the vcpkg build.

If that works, then submitting a patch to vcpkg to set it during the build phase of ffmpeg might do the trick.

**Comment by tomFlowee** [comment]
Ok, vcpkg is upstream? I didn't know that. I figured it was ladybird code.

I can't make this work, vcpkg just complains about how it's called:  
> vcpkg install ffmpeg

> Does setting TMPDIR in your environment fix this issue?

yes. Doing that prior to calling the Meta/ladybird.sh makes it work for me.

> If that works, then submitting a patch to vcpkg to set it during the build phase of ffmpeg might do the trick.

That would be ideal, indeed. But I'm clueless about vcpkg, and I checked that ffmpeg has had this in their configure since sept 2006, so I'll just assume I'm the only one with this issue and work around it.

If anyone from ladybird wants to pick this up, feel free to reopen. But I guess this doesn't belong here.

**Comment by tomFlowee** [comment]
If this ever comes up here again, upstream ticket I made: https://trac.ffmpeg.org/ticket/11382
