### ISSUE TITLE
[CSS Grid] Infinite recursion on https://shopify.com

### ISSUE THREAD

**Issue by awesomekling** [LadybirdBrowser/ladybird#2732]
Simplified reduction:
```html
<!doctype html><style>
    body {
        display: grid;
        max-height: fit-content;
    }
</style>hello
```

**Comment by Alonsocom** [comment]
https://github.com/LadybirdBrowser/ladybird/issues/2732#issue-2715778196
<!doctype html><style>
    body {
        display: grid;
        
    }
</style>hello
