### ISSUE TITLE
Use searchxNG as the default search engine

### ISSUE THREAD

**Issue by romulasry** [LadybirdBrowser/ladybird#2830]
With no logging.

**Comment by circl-lastname** [comment]
There is no default search engine, search is disabled in the default settings.

**Comment by AtkinsSJ** [comment]
If I understand correctly, SearXNG is software for running a search engine, and not an actual search engine website itself? Hosting that ourselves is out of scope for the Ladybird project. If there's a good SearXNG instance you can recommend, then you could add it to the list of built-in search engines though.
