### ISSUE TITLE
LibWeb/LibGfx: Load Emojis from fonts rather than individual PNG files

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#287]
The fallback for emojis should be contained in a font file. Either a system default font, or one that we ship ourselves. The many many emojis PNGs are fun to use and look at, but the organization is a bit unwieldy.

It would be nice to not have to install all these emoji files along with the browser in distribution packages as well.

**Comment by ranjanmangla1** [comment]
hi @ADKaster , would love to take this. Can we use noto color emoji for emojis?

**Comment by awesomekling** [comment]
> hi @ADKaster , would love to take this. Can we use noto color emoji for emojis?

We should honor whatever the system's preferred emoji font is.

**Comment by ADKaster** [comment]
Resolved in #1297
