### ISSUE TITLE
[Feature request] Make ladybird work on "financial websites" (house bank etc...) a priority.

### ISSUE THREAD

**Issue by rubyFeedback** [LadybirdBrowser/ladybird#2895]
Hey there ladybird devs,

I understand that you guys prioritize on bugs and simpler features, so it is perfectly fine to close this issue. The primary reason for the issue request here is to try to bring in an additional use case, and then perhaps, say, in some months, see a change in ladybird development that would help achieve the described goal here come closer to fruition, or even make it possible. I state this upfront so that you guys can close this and focus on bug reports etc...

So, before I describe the use case and feature request, let me first describe the background, and use case, as to why I filed this issue request today.

I am living in ~Central Europe and one important website I need is here (Erste Bank):

https://login.sparkasse.at/sts/oauth/authorize?response_type=token&client_id=georgeclient&state=

I usually use thorium as browser, which works fairly well. Today I had a hard time logging in. I did try
via opera and experienced the same issue. I then used firefox and all worked well; I could do the transaction I needed, close firefox and resume thorium.

Hopefully one day I can switch to ladybird; for the time, though, I am mostly using thorium. But in this
case, I thought ... "if I only use firefox for the job to log in to the online account of my bank account, why not use ladybird instead?" But, of course, I do not know how well ladybird already supports secure connections etc... It would be super-great if I could already use ladybird for this, rather than firefox.

The issue I had with thorium etc... was that after log in, a perpetually loading symbol was shown, and nothing else happened, e. g. that round circle that keeps on circling about in infinity. I think it was related to either cookies, or javascript. Anyway, just to explain the issue a bit; my objective, though, is to use ladybird rather than firefox eventually.

I do not know how well ladybird supports logging into a bank account yet. Perhaps some websites work and others do not. But I think I may not be the only one who would love to be able to use ladybird specifically in regards to transactions. This works in other browsers as well already (well, kind of, if we ignore the fact that it did not work for me with other browsers, so they tend to suck as well; except for firefox, but I can not use videos on Linux + firefox as I don't use pulseaudio, whereas thorium has no problem with audio; anyway, not going onto that side-discussion, just wanting to point out that "established browsers" can also suck for different reasons).

As I assume that secure transactions via the browser are super-important for many users, I would suggest that ladybird eventually focuses on this part in the future. Yes, many other things should work for ladybird, youtube videos, and what not, but I believe that for the top-ten-use cases, I think online banking and transactions via online shops, should most definitely be within the Top 10, perhaps even Top 5 use cases. It would also help adoption if that works well, IMO - and, as pointed out, I do not know how well it works right now. Perhaps it works well, but for the time being I simply use firefox in this regard.

Anyway - I don't want to make this issue request too long, so this was basically the main gist of my request. I am not saying this focus should be done "over night"; but perhaps it can be evaluated in some future meeting in a few months from now, and then more specific actions could be done, e. g. adding test cases, more summary report findings which other components have to be improved, and so forth. I assume that most of this is related to javascript in one way or another, so perhaps this is the main hurdle, although perhaps some HTML and CSS related aspect, as well as secure connections, may also have to be looked at more thoroughly.

Thank you for at the least reading this request, and as stated up front, please do feel free to close this issue here at any moment in time - hopefully after one or two ladybird dev had a look at the use case and rationale made here (e. g. "make financial transactions work well in ladybird").

**Comment by gmta** [comment]
Hi @rubyFeedback, the issues section of this project is for reporting actual issues, not discussing potential outcomes without even having tried Ladybird yourself.

If you want to talk to someone about Ladybird, consider [joining our Discord](https://discord.gg/nvfjVJ4Svh).

If at some point you find an actual bug or a website that doesn't work in Ladybird, feel free to open an issue.

**Comment by ADKaster** [comment]
@rubyFeedback Your opening comment on the issue is a lot of storytelling, and not a lot of technical details. 

> I do not know how well ladybird supports logging into a bank account yet. Perhaps some websites work and others do not. 

Posting an issue on our issue tracker without even trying it out for your desired use case is not helpful for our development.

A more actionable issue might go something like this:

> Hi, I tried `<0banking website url>`. and it seems to load properly. However, I am unable to log in. The logs said that Web API methods `<x, y and z>` are marked as FIXME, and there were javascript errors that tried to access `<Web API Foo that does not exist on ladybird's window object>`.
>
> After looking at the site, it looks like <screenshot>
>
> It looks like in order to support this website, Ladybird will need to implement
> - `spec link 1`
> - `spec link 2`
> - `mdn link if you do not know how to get to the spec link`

Thanks for your interest in Ladybird, but I think that your understanding of GitHub issues does not match the project's expectations. Our issue tracker should not be a place to blog about potential improvements to the web, but a place to discuss development of specific features, to address specific bugs, and to prioritize specific features based on which websites and categories of websites they affect.
