### ISSUE TITLE
CSS: bottom 0% broken

### ISSUE THREAD

**Issue by Hexeption** [LadybirdBrowser/ladybird#325]
To replicate the issue here: 
```html
<div style="
    background: red;
    height: 100%;
    max-height: 320px;
    position: absolute;
    top: auto;
    bottom: 0%;
    left: 0%;
    right: 0%;"></div>
```

(left is ladybird right is safari)
![Screenshot 2024-07-01 at 2 08 13 am](https://github.com/LadybirdBrowser/ladybird/assets/4052647/5b3d5540-593b-483b-8c17-280e8a678bda)

**Comment by nico** [comment]
Fixed?

**Comment by dzfrias** [comment]
Just verified that this is indeed fixed.
