### ISSUE TITLE
about:blank change 

### ISSUE THREAD

**Issue by Ygarr** [LadybirdBrowser/ladybird#331]
How to make such  default art for browser when no pages are opened?
![image](https://github.com/LadybirdBrowser/ladybird/assets/14309871/0797dad3-d14c-4428-aa6b-88bad4c30f55)

**Comment by circl-lastname** [comment]
This is not a bug or issue.

**Comment by trflynn89** [comment]
about:blank is a standardized page, which is expected by websites to be - unsurprisingly - blank. We won't be injecting logos into that page.
