### ISSUE TITLE
Decentralized DNS: native integration of .bit domains (via Namecoin)

### ISSUE THREAD

**Issue by noospheer** [LadybirdBrowser/ladybird#332]
Given Ladybird is building from the ground up, has the team considered native integration of support for .bit TLD domains using the **Namecoin** blockchain? Decentralized DNS is the future...

Namecoin (NMC) was the very first bitcoin fork (2011) and was envisioned by Satoshi Nakamoto in this post as ‘BitDNS’… Namecoin is essentially Satoshi’s only altcoin https://bitcointalk.org/index.php?topic=1790.msg28696#msg28696

As NMC is merge-mined with bitcoin, it has a high hash rate, making it ~equally as secure (as long as SHA-256 is not broken). A good explainer on .bit is here: https://www.namecoin.org/dot-bit/ 1](https://www.namecoin.org/dot-bit/

The namecoin dev team is small, but active and long-time dedicated, and some tender loving care like a proper native integration from a major browser will help realize the project’s vision of a more robust and decentralized web. I am not on the team but can facilitate comms. The lead NMC dev is @JeremyRand https://github.com/JeremyRand

Crypto OGs will remember that NMC was once a top contender in terms of market cap.

I've filed similar requests for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1686098

and Brave https://community.brave.com/t/native-integration-of-bit-domains-via-namecoin-nmc/548696

**Comment by ADKaster** [comment]
Hi!

Thanks for your interest in Ladybird. Going by your other opened feature requests, it sounds like this is not well-supported by other browsers?

At this time, we’re only interested in implementing technologies that are already in wide use on the web and supported by other browsers. Once there's a WhatWG standards track proposal in the works that other engines have confirmed positive standards positions on, we can take an other look.

**Comment by noospheer** [comment]
Thanks for reply :) I wonder, if you're waiting for others to lead on something like deploying decentralized DNS, what features do you expect to draw new users to Ladybird with (since in your planned development methodology, those features are already deployed in other browsers)?

**Comment by AtkinsSJ** [comment]
The main selling point is that we're completely independent of Google. Every major browser is either Chrome in a suit, or paid by Google to use their search by default. (There are a few other independent browsers, but generally they're a lot more limited. Eg, lynx is not a real option for most people.)

**Comment by noospheer** [comment]
That's a good sell, but Brave is effectively a de-googled Chrome with a bunch of privacy features, and is free/open as well... Wouldn't it be popular to trailblaze on a nontrivial feature (such as decentralized DNS) so that there is something Ladybird offers which the others need to catch up to you on?

If the mission is to champion the open web, why not support under-utilized technologies which do just that (such as .bit domains resolved on the blockchain, backed by the bitcoin mining pool). It's 2024 and the world is still ~100% reliant on ICANN to make the web work, a single organization headquartered in California.

**Comment by JeremyRand** [comment]
Sorry I took so long to post here, things have been busy on my end.

> Once there's a WhatWG standards track proposal in the works that other engines have confirmed positive standards positions on, we can take another look.

@ADKaster It doesn't really make sense to expect WHATWG to standardize Namecoin. WHATWG is for *web* standards; Namecoin is not a web technology, it's a naming-layer technology. It would be like wondering why WHATWG hasn't standardized DNSSEC or DoH -- it's simply outside of their scope.
