### ISSUE TITLE
rebaseline-libweb-test doesn't work on macOS

### ISSUE THREAD

**Issue by lukewarlow** [LadybirdBrowser/ladybird#358]
To get this command working on macOS I had to change the last line.

Before:
`./bin/headless-browser $mode_flag --layout-test-mode $input_dir/$test_name.html > $expected_dir/$test_name.txt`

After:

`./bin/Ladybird.app/Contents/MacOS/headless-browser $mode_flag --layout-test-mode $LADYBIRD_SOURCE_DIR/Tests/LibWeb/$input_dir/$test_name.html > $LADYBIRD_SOURCE_DIR/Tests/LibWeb/$expected_dir/$test_name.txt`

The LADYBIRD_SOURCE_DIR env variable is also not documented afaik.

**Comment by AtkinsSJ** [comment]
I think this was fixed by #445. I've definitely used this script on macOS since then without noticing any issues. (Apart from LADYBIRD_SOURCE_DIR being undocumented. :sweat_smile: )
