### ISSUE TITLE
No gap in flex column layout with `justify-content: space-between`

### ISSUE THREAD

**Issue by aplefull** [LadybirdBrowser/ladybird#364]
Reduced example:

```HTML
<style>
    body {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        gap: 20px;
    }

    .box {
        background-color: crimson;
        width: 40px;
        height: 40px;
    }
</style>

<div class="box"></div>
<div class="box"></div>
```

How it looks in Chrome and Firefox:   

![image](https://github.com/LadybirdBrowser/ladybird/assets/10453915/59414077-3ca5-4ec4-8f19-4ce08fa63912)

Ladybird:   

![image](https://github.com/LadybirdBrowser/ladybird/assets/10453915/9ee48a0e-e78c-4d7e-a7bd-ce8c4d197a61)

**Comment by Gingeh** [comment]
This issue was fixed in #437
