### ISSUE TITLE
flatpak release for linux

### ISSUE THREAD

**Issue by RustoMCSpit** [LadybirdBrowser/ladybird#378]
flathub.org is the main distribution method for linux

**Comment by Tweekism** [comment]
I don't think the project is at that stage yet.

**Comment by circl-lastname** [comment]
2026.

**Comment by svin24** [comment]
I could try making a sample flatpak file but i don't think it would be useful.

**Comment by trflynn89** [comment]
We are not focused on package distribution at this time.

**Comment by samolukadjo** [comment]
Maybe in the project's own flatpak “store” that could be used to distribute it more easily to testers at some point in the future, but that all seems far off

**Comment by orowith2os** [comment]
If Ladybird would like to set up a flatpak repo to ship nightly builds to users, I may be able to assist with that, assuming Ladybird can provide a server to host it on.

Per-commit bundles for CI would also be neat.
