### ISSUE TITLE
Web 3 Support

### ISSUE THREAD

**Issue by kehiy** [LadybirdBrowser/ladybird#384]
In this PR I suggest supporting web3 and decentralized web components in the ladybird.

There is prior art from Brave browser to support web3 but it's not a sull and well support. Supporting IPFS links and CIDs. Supporting ENS and TON DNS domains. supporting IPFS website and TON websites. Also, a good and secure support of nostr-based social media, for example, built-in signer support.

These are examples that can be supported on a new browser which makes it the future browser IMO.

**Comment by joeyboli** [comment]
NOPE
