### ISSUE TITLE
Ladybird not doing proper cleanup after exiting

### ISSUE THREAD

**Issue by balika0105** [LadybirdBrowser/ladybird#403]
When closing the main Ladybird window, some processes stay active without any Ladybird windows open.
Expected behaviour should be the program closing child processes and anything in regards to itself.
See image below for the processes
![image](https://github.com/LadybirdBrowser/ladybird/assets/40917873/82c350a7-2f1e-46ff-a9f8-a191e6350891)

**Comment by kalenikaliaksandr** [comment]
This bug should've been solved by https://github.com/LadybirdBrowser/ladybird/pull/319
Please reopen if the problem is still reproducible.
