### ISSUE TITLE
Why, as a browser developed from scratch, is it not developed using Rust?

### ISSUE THREAD

**Issue by izdbrave** [LadybirdBrowser/ladybird#407]
Nowadays, there's a trend of migrating from C++ to Rust, so why does Ladybird still choose to develop in C++ instead of Rust?

**Comment by 0GreenClover0** [comment]
There is a FAQ on https://ladybird.org/ where this exact question is answered

![obraz](https://github.com/LadybirdBrowser/ladybird/assets/36564831/d5db7b5d-ca47-452a-b0e9-834aa401537e)

**Comment by izdbrave** [comment]
> There is a FAQ on https://ladybird.org/ where this exact question is answered
> 
> ![obraz](https://private-user-images.githubusercontent.com/36564831/345659286-d5db7b5d-ca47-452a-b0e9-834aa401537e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTg5MzYsIm5iZiI6MTcyMDA1ODYzNiwicGF0aCI6Ii8zNjU2NDgzMS8zNDU2NTkyODYtZDVkYjdiNWQtY2E0Ny00NTJhLWIwZTktODM0YWE0MDE1MzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjFkMGE5NTg4M2ZiODdjMGFiZTg0YTNhZmUxZDRiYWUzYTU1ZmYzNmZhNjM4ZTEzNjBjYTJmODk1Mzg1MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98aPT9PdP9Qb8H4yMRcG0asV3SM1lnKUI2hhVTefrt8)

 Thanks! If it's a browser built from the ground up in Rust, that would be even more promising.

**Comment by versecafe** [comment]
To be fair the disclaimer does say it was in part due to the constraints of Serenity and Andreas's initial preference as the project is starting to grow faster with a larger community it might make sense to look into binding rust with CXX to the existing code base and swapping out certain sections as time goes on

> Wish it was all rust, C++ tooling ecosystem is a nightmare, but a full port would be unlikely and a Rust + C++ hybrid would still require native tooling, and bindings to things like Obj-C / Swift for macOS UI still usually requires native tooling see [Zed](https://github.com/zed-industries/zed) for a good example of that.

**Comment by dertuxmalwieder** [comment]
> Nowadays, there's a trend of migrating from C++ to Rust

Honestly, "it's the trend" is the worst possible reason to use a specific programming language.

**Comment by markand** [comment]
> Nowadays, there's a trend of migrating from C++ to Rust, so why does Ladybird still choose to develop in C++ instead of Rust?

serenity is written in C++ from the ground up and so for the entire system and apps. if you want an entire OS in your favorite language, you can have a look at [redox](https://www.redox-os.org/).

"new" projects do not require to be written in rust.

**Comment by dante-e-v** [comment]
> > There is a FAQ on [ladybird.org](https://ladybird.org/) where this exact question is answered
> > ![obraz](https://private-user-images.githubusercontent.com/36564831/345659286-d5db7b5d-ca47-452a-b0e9-834aa401537e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTg5MzYsIm5iZiI6MTcyMDA1ODYzNiwicGF0aCI6Ii8zNjU2NDgzMS8zNDU2NTkyODYtZDVkYjdiNWQtY2E0Ny00NTJhLWIwZTktODM0YWE0MDE1MzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjFkMGE5NTg4M2ZiODdjMGFiZTg0YTNhZmUxZDRiYWUzYTU1ZmYzNmZhNjM4ZTEzNjBjYTJmODk1Mzg1MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98aPT9PdP9Qb8H4yMRcG0asV3SM1lnKUI2hhVTefrt8)
> 
> Thanks! If it's a browser built from the ground up in Rust, that would be even more promising.

As some good web tech has been built with Zig people wonder about that language as well for building a web browser and/or engine.

There's still the Servo web engine project and I wouldn't be surprised if Ladybird takes some inspiration from that. Though Servo is more modular so projects like Tauri want it to make building apps even leaner and work faster.

**Comment by is-this-c** [comment]
> If it were written in Rust, it wouldn't be worth touching.

Too bad C++ is crusty. 0-days? No thanks.
