### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by asutoshvariar** [LadybirdBrowser/ladybird#412]
Using [this](https://tests.caniuse.com/avif) for testing AVIF support, and Ladybird doesn't seem to support it. As AVIF is supported on all major platforms, adding this to Ladybird ensures feature parity.

**Comment by asutoshvariar** [comment]
#455 is a draft PR aiming to fix this, issue will be closed when PR gets merged.

**Comment by doctortheemh** [comment]
https://github.com/LadybirdBrowser/ladybird/pull/455 merged, should resolve this issue.

**Comment by asutoshvariar** [comment]
Yep, closing now.
