### ISSUE TITLE
add dependency to Documentation/BuildInstructionsLadybird.md

### ISSUE THREAD

**Issue by greenbla** [LadybirdBrowser/ladybird#413]
under "Required packages include, but are not limited to:"
we should add libssl-dev
otherwise build command "./Meta/ladybird.sh run ladybird"  gives the following error "-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable "

**Comment by ADKaster** [comment]
This error is almost always related to CMake being too old, and needing to be built from source.

If anything we should probably stop trying to do that and just complain outright if cmake is less than our minimum required...

**Comment by ADKaster** [comment]
That being said, this is closed by #374 :sweat_smile:
