### ISSUE TITLE
Certificate verification error

### ISSUE THREAD

**Issue by weanti** [LadybirdBrowser/ladybird#414]
git version: 698a95d2dee0ba7e9a3f1c39af5459ba506c445f
OS: Void Linux X86_64
A specific website is not working with the following message:
original output:
`verify_chain: Next certificate in the chain is not the issuer of this certificate`
my modified output:
`verify_chain: Next certificate in the chain {\CN=distrowatch.com} is not the issuer of this certificate \O=Let's Encrypt\CN=R11\C=US`
The website: `https://www.distrowatch.com`
I debugged the problem, but I do not have enough knowledge about the context.
What I have found so far:
- the error message comes from TLSv12.cpp: Context::verify_chain
- the content of local_chain is the following:
  * idx 0, subject \CN=distrowatch.com, issuer \O=Let's Encrypt\CN=R11\C=US
  * idx 1, subject \CN=distrowatch.com, issuer \O=Let's Encrypt\CN=R11\C=US
  * idx 2, subject \O=Let's Encrypt\CN=R11\C=US, issuer \O=Internet Security Research Group\CN=ISRG Root X1\C=US

I debugged the certificate reading as well in TLSv12::handle_certificate
Here is some debug data provided by some of my own dbgln() calls:
```
payload size: 4019 buffer length: 4020
total length: 4016
certificate_size 4013

reading next certificate data starting at pos 6
(here comes the 3 byte data for the cert size)
parse cert res_cert 9 with length certificate_size_specific 1357
cert read: {\CN=distrowatch.com} {\O=Let's Encrypt\CN=R11\C=US}

reading next certificate data starting at pos 1366
(here comes the 3 byte data for the cert size)
parse cert res_cert 1369 with length certificate_size_specific 1357
cert read: {\CN=distrowatch.com} {\O=Let's Encrypt\CN=R11\C=US}

reading next certificate data starting at pos 2726
(here comes the 3 byte data for the cert size)
parse cert res_cert 2729 with length certificate_size_specific 1290
cert read: {\O=Let's Encrypt\CN=R11\C=US} {\O=Internet Security Research Group\CN=ISRG Root X1\C=US}

```

**Comment by ADKaster** [comment]
You can also try running with `--certificate=/path/to/your/root/cert/in/pem/format` to see if the page loads with your distro-provided root certificates

**Comment by fdellwing** [comment]
While it might be a good idea to update our cacert. The actual problem here is that they fucked up their chain.

> 
    idx 0, subject \CN=distrowatch.com, issuer \O=Let's Encrypt\CN=R11\C=US
    idx 1, subject \CN=distrowatch.com, issuer \O=Let's Encrypt\CN=R11\C=US
    idx 2, subject \O=Let's Encrypt\CN=R11\C=US, issuer \O=Internet Security Research Group\CN=ISRG Root X1\C=US

They send the local certificate twice before sending the correct intermidiate. Other browsers seems to handle this situation gracefully, we don't.

So if we want to match other browsers behaviour here, we would need some kind of "drop this cert in the chain and try the next one" type of fallback.

**Comment by kvelicka** [comment]
FWIW I'm seeing the same issue on distrowatch, on Ubuntu 24.04

**Comment by fdellwing** [comment]
I think the "correct" behaviour we should implement is, to just drop any certificate on the ground that we already saw earlier in the chain as it can never be a correct element in the chain a second time.

**Comment by weanti** [comment]
My knowledge of certificates and TLS is very limited, but I may have an explanation what we are seeing. I found a StackOverflow thread:
[https://stackoverflow.com/questions/50857898/lets-encrypt-ssl-certificate-send-twice-in-tls-handshake](https://stackoverflow.com/questions/50857898/lets-encrypt-ssl-certificate-send-twice-in-tls-handshake)
It is explained in this thread that with certain Apache configuration the self signed certificate may be sent twice: once as a standalone certificate and once as the part of the certificate chain.
I'm not sure distrowatch uses Apache.
Anyway, I think the easiest approach would be to skip duplicate items in the chain as @fdellwing recommended.

**Comment by kvelicka** [comment]
I did some debug logging for my issue too which seems somewhat different, at least not Let's Encrypt related:


```
idx 0 issuer \L=Salford\O=Sectigo Limited\CN=Sectigo RSA Domain Validation Secure Server CA\ST=Greater Manchester\C=GB subject \CN=www.REDACTED_INTERNAL_DOMAIN.com
idx 1 issuer \L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB subject \L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB
```

Hopefully I'm not leaving out important information by redacting the domain I'm trying to reach - would prefer to not have to disclose it publicly ideally!

**Comment by fdellwing** [comment]
Your server is sending a root certificate (but should not) and it not sending the intermediate certificate. This is not a Ladybird problem, all other browsers just "fix" the chain automatically without annoying the user.

See: https://support.sectigo.com/articles/Knowledge/Sectigo-Intermediate-Certificates

**Comment by kvelicka** [comment]
Do you think that ladybird will [at some point] do the "chain fixing" too? Is it worth opening a new ticket for that?

**Comment by fdellwing** [comment]
At some point? Probally. In the foreseeable future? Doubt. It's not that easy to implement and maintain.

**Comment by weanti** [comment]
Maybe this is a kind of situation when user confirmation is required? An "Accept risk and proceeed" like button would be acceptable? If yes, then I might be able to send a PR.

**Comment by fdellwing** [comment]
Yes that would be the perfect scenario.

One would need to set `m_context.options.validate_certificates` to false so that when we reach this line, we skip the chain verification.

https://github.com/LadybirdBrowser/ladybird/blob/bfc9dc447f42eb9d7d0927721291d1b528b3125d/Userland/Libraries/LibTLS/TLSv12.cpp#L248-L251

**Comment by ctz** [comment]
> While it might be a good idea to update our cacert. The actual problem here is that they fucked up their chain.

This is not correct. In TLS the first certificate is the one for the server, and the remainder are _an unordered list_ of any other certificates that may appear in any possible chain to trusted roots. In older versions of (TLS1.2 and before) this was allegedly meant to be ordered, but a verifier that relies on that won't be able to find valid chains that have cross-signed roots.

So the supplied certificates, a valid chain would be idx 0, idx 2 with the trusted root being ISRG Root X1.

ref: RFC8446 S 4.4.2

>  all implementations SHOULD be prepared to handle
>   potentially extraneous certificates and arbitrary orderings from any
>   TLS version, with the exception of the end-entity certificate which
>   MUST be first.

For background, Ryan Sleevi has a great blog post on this: https://medium.com/@sleevi_/path-building-vs-path-verifying-the-chain-of-pain-9fbab861d7d6

**Comment by fdellwing** [comment]
While we do not support TLS1.3, we might want to support this anyway. But that seems like a bigger task.

**Comment by tombigel** [comment]
I wanted to start collecting bugs and gaps on sites generated by the Wix platform (Websites made on Wix are between 3-4% of the web right after Shopify and Wordpress)
 and the `verify_chain: Next certificate in the chain is not the issuer of this certificate`  issue happens for *all* websites created on the Wix platform, on multiple subdomains.

I don't have much knowledge about TLS etc. to say whether Wix does something wrong here or not, just that it works and always worked on every other browser and passes whatever certificate testing online tool I throw at it.

I locally edited `TLSv12.cpp` to just ignore this error and print the subject and issuer of the certificate and the parent certificate,
So for example when opening https://wix.com (which is build with Wix) I immediately get

```
174089.191 RequestServer(14421): verify_chain: Next certificate in the chain is not the issuer of this certificate:
174089.191 RequestServer(14421): - Parent Subject: {\CN=*.wix.com}
174089.191 RequestServer(14421): - Parent Issuer: {\O=Let's Encrypt\CN=R11\C=US}
174089.191 RequestServer(14421): - Subject: \CN=*.wix.com
174089.191 RequestServer(14421): - Issuer: \O=Let's Encrypt\CN=R11\C=US
```  

but since I don't fail I continue to get this for other resources on the page, I also checked for some sites that are not served directly from a "wix.com" domain, all resources loading fails on these (parastorage.com and wixstatic.com are CDN endpoints):
```
174091.131 RequestServer(14421): verify_chain: Next certificate in the chain is not the issuer of this certificate
174091.131 RequestServer(14421): - Parent Subject: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.131 RequestServer(14421): - Parent Issuer: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.131 RequestServer(14421): - Subject: \CN=*.parastorage.com
174091.131 RequestServer(14421): - Issuer: \L=Salford\O=Sectigo Limited\CN=Sectigo RSA Domain Validation Secure Server CA\ST=Greater Manchester\C=GB
174091.135 RequestServer(14421): verify_chain: Next certificate in the chain is not the issuer of this certificate
174091.135 RequestServer(14421): - Parent Subject: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.135 RequestServer(14421): - Parent Issuer: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.135 RequestServer(14421): - Subject: \CN=*.parastorage.com
174091.135 RequestServer(14421): - Issuer: \L=Salford\O=Sectigo Limited\CN=Sectigo RSA Domain Validation Secure Server CA\ST=Greater Manchester\C=GB
174091.140 RequestServer(14421): verify_chain: Next certificate in the chain is not the issuer of this certificate
174091.140 RequestServer(14421): - Parent Subject: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.140 RequestServer(14421): - Parent Issuer: {\L=Salford\O=Comodo CA Limited\CN=AAA Certificate Services\ST=Greater Manchester\C=GB}
174091.140 RequestServer(14421): - Subject: \CN=*.wixstatic.com
174091.140 RequestServer(14421): - Issuer: \L=Salford\O=Sectigo Limited\CN=Sectigo RSA Domain Validation Secure Server CA\ST=Greater Manchester\C=GB
```

**Comment by weanti** [comment]
From my point of view, the original problem is solved. I checked it in version a7a24fed6882a7c436e488c78e9b7383753f6f56.

**Comment by fdellwing** [comment]
This should no longer be relevant with the new `libcurl` backend.
