### ISSUE TITLE
Crash when loading Google Maps

### ISSUE THREAD

**Issue by TanukiKabuki** [LadybirdBrowser/ladybird#419]
While browsing Google owned domains, specifically Google.com, Youtube, Gmail, Google Maps image assets are taking exceedingly long to open. Google Maps simply crashes the browser. Startpage, DuckDuckGo function fine however. 
Reviewing the terminal read out, this seems to be related to not having a decoder in place, however it is a JPEG image format, initially thinking that it might have been a WEBP instead. Startpage.com logo image is SVG formatted and loads fine however.

**Comment by awesomekling** [comment]
Hi there! This bug report has way too many things going on at the same time. If I read this right, what you are reporting is essentially:

- google.com takes a long time to open
- YouTube takes a long time to open
- GMail takes a long time to open
- Google Maps image assets are taking exceedingly long to open
- Google Maps crashes the browser
- There may be some issue with not having an image decoder in some context

We are aware that many websites take a long time to open. Many parts of our stack are slow and unoptimized. We don't require bugs about every site that loads slowly :)

The main actionable issue I see here is how Google Maps crashes the browser, so let me repurpose this bug for that, and see if we can fix it.
