### ISSUE TITLE
Ladybird will not install on fedora 40

### ISSUE THREAD

**Issue by SomeDudeBrosky** [LadybirdBrowser/ladybird#430]
I am running Fedora 40 (Gnome) and followed the installation instructions, and although qt6 linguist/designer installed, the /meta, /ladybird, and ladybird.sh do not exist on my system, and I am unable to run them as they did not install. I fully followed all instillation steps.

**Comment by Tweekism** [comment]
The build instructions assumes you are a developer and have already cloned the git repo to your local computer.

So at a terminal you'd type `git clonehttps://github.com/LadybirdBrowser/ladybird.git` and that will download the files. You can then `cd ladybird` into that folder and you'll find the Meta and ladybird.sh files you are looking for in there.

**Comment by SomeDudeBrosky** [comment]
Thank you. Build instructions should be more clear, as that is not mentioned as a prerequisite.

**Comment by ADKaster** [comment]
I think that basic GitHub usage like this is adequately covered in [GitHub's documentation](https://docs.github.com/en/get-started) or other "how to use git and the command line" tutorials. We have to establish our baseline somewhere, and knowing how to clone a repository and navigate to it seems like as good a place as any.

Welcome to open source though! If you have any issues with build steps of the project, please hop into our discord in the #build-problems channel.
