### ISSUE TITLE
CSS accent-color property not supported for all elements

### ISSUE THREAD

**Issue by wklug** [LadybirdBrowser/ladybird#466]
Description: Setting the `accent-color` in an `<input type="range">` and `<progress>` elements, is not being honored. It is working fine for `<input type="checkbox">` and `<input type="radio">`
OS: MacOS Sonoma 14.2.1
Reference: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color)
Reference: [Can I use](https://caniuse.com/mdn-css_properties_accent-color)
Version: Master - commit 172e080b0730024bb92be2e921d849c9bcd16bf0
Screenshots:
|   Brave   |   Ladybird   |
| ---- | ---- |
| <img width="331" src="https://github.com/LadybirdBrowser/ladybird/assets/22845981/5746eb45-6fe4-4494-bd74-7ae0e06b0c81"> | <img width="475" src="https://github.com/LadybirdBrowser/ladybird/assets/22845981/5f0af3b2-47f8-4974-877c-225fb723178d"> |

Code to reproduce:

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      input[type=checkbox] {
        accent-color: #d2e148;
      }

      input[type=radio] {
        accent-color: #651195;
      }

      input[type=range] {
        accent-color: #b935b3;
      }

      progress {
        accent-color: #86b935;
      }
    </style>
  </head>
  <body>
    <h3>Checkboxes:</h3>
    <input type="checkbox" id="brave" name="brave" value="Brave" checked>
    <label for="brave">Brave Browser</label>
    <br />
    <input type="checkbox" id="ladybird" name="ladybird" value="Ladybird" checked>
    <label for="ladybird">Ladybird Browser</label>

    <h3>Radio buttons:</h3>
    <input type="radio" id="brave" name="browser" value="Brave">
    <label for="brave">Brave Browser</label>
    <br/>
    <input type="radio" id="ladybird" name="browser" value="Ladybird" checked>
    <label for="ladybird">Ladybird Browser</label><br>

    <h3>Input type range:</h3>
    <label for="volume">Music Volume:</label>
    <input type="range" id="volume" name="volume" min="0" max="10" value="4">

    <h3>Progress:</h3>
    <label for="download">Downloading progress:</label>
    <progress id="download" value="20" max="100"> 20% </progress>
  </body>
</html>
```

I noticed another issue with the `input type="range"`: There's no visual indication of the value, all the bar is displaying a single color.

**Comment by simonkrauter** [comment]
Anyone knows, how to access `computed_values()` from `HTMLInputElement::create_range_input_shadow_tree()`?
