### ISSUE TITLE
:focus doesn't update unless moused over

### ISSUE THREAD

**Issue by vpzomtrrfrt** [LadybirdBrowser/ladybird#471]
Sample page:
```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			textarea {
				color: lime;
			}
			textarea:focus {
				color: red;
			}
		</style>
	</head>
	<body>
		<textarea>a</textarea>
		<textarea>b</textarea>
	</body>
</html>
```

These textareas should turn red when focused, but instead they only seem to update their color when triggering mouseenter or mouseleave on the textarea

**Comment by tcl3** [comment]
If you look at `HTMLInputElement::did_lose_focus()` and `HTMLInputElement::did_receive_focus()` it looks like the style of `m_text_node` is not invalidated. I believe calling `m_text_node->invalidate_style()` (or equivalent) should fix this issue.

It looks like this issue also affects `HTMLInputElement` and I think the solution would be the same there too.
