### ISSUE TITLE
needed vulkan to execute

### ISSUE THREAD

**Issue by greenbla** [LadybirdBrowser/ladybird#475]
On running ./ladybird.sh run ladybird i got
"error while loading shared libraries: libvulkan.so.1: cannot open shared object file: No such file or directory".
To fix, i installed vulcan-sdk by following https://vulkan.lunarg.com/doc/view/latest/linux/getting_started_ubuntu.html
Does this need to be put in Documentation/BuildInstructionsLadybird.md ?
also, is there a more compact alternative than entire vulkan-sdk (>300mb) ?

**Comment by ADKaster** [comment]
On ubuntu, the [mesa-vulkan-drivers](https://packages.ubuntu.com/jammy/mesa-vulkan-drivers) package seems to provide the required libs. Or just libvulkan1 itself. But I'm not sure how my install ended up with these libs... I assumed one of the already specified dependencies would have installed it. e.g. the Qt6 ones, or libgl1-mesa-dev

**Comment by kalenikaliaksandr** [comment]
should've be fixed by https://github.com/LadybirdBrowser/ladybird/commit/22d7aa53fa52bdf71eef667eb58d142b10d4ba74
