### ISSUE TITLE
Add font debugging panel to inspector

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#485]
Font resolution is complicated, and so the CSS describing what font should be used does not necessarily match the font that is used. It would be useful to have a tool in the inspector that describes the used fonts for an element, and possibly those for the whole page, so that we can more easily debug issues like #351 and #480. (Note that a single element may use multiple fonts, if some characters are not available in the preferred font.)

Firefox and Chrome both include some kind of font inspection. In Chrome, it's a small panel at the bottom of the Computed tab (bottom right):
![image](https://github.com/LadybirdBrowser/ladybird/assets/222642/401ef887-65b2-43bd-944c-dc8d183e5e37)

And Firefox has its own Fonts tab, which additionally lists all the fonts and lets you manipulate the font properties:
![image](https://github.com/LadybirdBrowser/ladybird/assets/222642/56c37a58-755d-42b3-b740-01787983181b)

**Comment by TobyAsE** [comment]
Can this be closed? Maybe some specific feature requests for the font inspector can become independent issues.

**Comment by AtkinsSJ** [comment]
Sure, we do have it now at least.
