### ISSUE TITLE
Default-appearance `<input type=range>` is rendered too small

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#512]
Discovered this while testing the `Base/res/html/misc/input-range.html` test page:

![image](https://github.com/LadybirdBrowser/ladybird/assets/222642/be4f5994-6871-4832-9657-09e0fd69717e)

The two with default appearance are rendered quite narrow, but the others have the correct width. The hitbox still fills the entire width, as shown by the focus highlight. It's a little hard to describe, but to set the slider at 50%, you'd need to click half way along the outlined box, not half way along the rendered slider.

I'm sure this worked correctly at some point so I'm marking it as a regression.

**Comment by simonkrauter** [comment]
This happens only the the width is given in percent.
