### ISSUE TITLE
Default value of `<input type=range>` is 0 instead of 50%

### ISSUE THREAD

**Issue by simonkrauter** [LadybirdBrowser/ladybird#520]
When no "value" is specified for an `<input type=range>` element, the value should be in the middle between `min` and `max`.

Test page: `Base/res/html/misc/input-range.html`

Screenshot Ladybird:
![ladybird](https://github.com/LadybirdBrowser/ladybird/assets/8593614/93499124-000b-43f0-ba20-ea04f8c5ee20)

Screenshot Chrome:
![chrome](https://github.com/LadybirdBrowser/ladybird/assets/8593614/2ab42cff-3308-420d-ae85-ebf57779bccd)

Spec: https://html.spec.whatwg.org/multipage/input.html#dom-input-value-default

**Investigation**

`HTMLInputElement::value_sanitization_algorithm()` implements the algorithm in the line
```cpp
return JS::number_to_string(minimum + (maximum - minimum) / 2);
```
but it seems that it is never called at initialization and `m_value` is an empty string.

**Comment by sideshowbarker** [comment]
> I have found a solution. I will submit it after #513 has merged, because the code changes overlap.

I’m curious to see your patch. A few hours ago (last night my time) I had started to look myself at writing up a patch for it — and had made some progress, but not yet a full fix.
