### ISSUE TITLE
LibWeb/CSS: transform rotate function not properly rotating around Z axis

### ISSUE THREAD

**Issue by samfry13** [LadybirdBrowser/ladybird#524]
Using the `transform: rotate(...)` or `rotateZ(...)` functions do not behave as expected:

| Ladybird Screenshot | Arc (Chromium) Screenshot |
| - | - |
| ![image](https://github.com/LadybirdBrowser/ladybird/assets/25012814/23cd30cf-9845-471c-8834-1fc288a98cc2) | ![image](https://github.com/LadybirdBrowser/ladybird/assets/25012814/2a5c8cae-bde8-4511-a3d6-243f00c2ac6e) |

Reproducible html:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <style>
            #test {
                width: 50px;
                height: 50px;
                background-color: blue;
                transform: rotate(12deg);
            }
        </style>
    </head>
    <body>
        <div id="test"></div>
    </body>
</html>
```

**Comment by kalenikaliaksandr** [comment]
Painter that uses LibGfx does not support CSS rotation transform. we are working on a new Skia painter that is currently available under a flag `--enable-skia-painting` where attached reduction does display correctly.
