### ISSUE TITLE
Build instructions for Fedora missing the required `nasm` package.

### ISSUE THREAD

**Issue by ludovit-as** [LadybirdBrowser/ladybird#530]
As the title says, the `nasm` package is not included in the provided `dnf` command. 

https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/BuildInstructionsLadybird.md

**Comment by simonkrauter** [comment]
Fixed by https://github.com/LadybirdBrowser/ladybird/commit/2a36fd2aed2c378762aac6dc43da28df7c25a183
