### ISSUE TITLE
can't use Ladybird to build the ladybird.org site sources

### ISSUE THREAD

**Issue by mrcolbyrussell** [LadybirdBrowser/ladybird#540]
This is the tracking bug for the LadybirdBrowser/ladybird side of the problem described in [LadybirdBrowser/ladybird.org issue #25](https://github.com/LadybirdBrowser/ladybird.org/issues/25) and the changes that need to be made to Ladybird before the Steps to Reproduce (copied below) work.

It should be possible to write a blog post for the ladybird.org website and then build the ladybird.org site/blog using Ladybird, without needing bun.

----

Steps to reproduce:

1. Open Ladybird
2. Download the ladybird.org site sources from <https://github.com/LadybirdBrowser/ladybird.org>
3. Open a new tab in Ladybird and point it at the file from the ladybird.org repo that describes how to build the site
4. Follow the instructions on that page that says to use a file picker to open the source tree (or drag and drop the repo directory into Ladybird)

Expected results:

It works.

Actual results:

There is no such file with instructions as described in steps 3 and 4.  Dragging and dropping the website source code into Ladybird does nothing.  The README says use `bun install`.

**Comment by versecafe** [comment]
If you run the ladybird.org dev script or build the site out and serve the static HTML this works perfectly fine, any failures in dev script on Ladybird browser are due to LibJS being unstable and dev using Vite for HMR, when serving the final site you will have no issues, also you really should be pointing at the port serving the site not the raw files

**Comment by versecafe** [comment]
Ladybird doesn't build the site source? it just renders webpages, Astro code gets compiled into a webpage that ladybird can then run

**Comment by trflynn89** [comment]
> It should be possible to ... build the ladybird.org site/blog using Ladybird, without needing bun.

No, there is no reason this should be possible. Ladybird is not and will not be a compiler for Astro files.

**Comment by trflynn89** [comment]
None of us are confused about what you said. Your stated goal is just not possible, nor should it be. Ladybird does not "build" websites in any manner. And we will not replace the website with plain HTML files.

**Comment by versecafe** [comment]
> ... This bug is not about Ladybird being "a compiler for Astro files". It's about being able to build the ladybird.org ... without needing bun. 

As stated before the site being plain HTML files was unmaintainable so a build step was added, this build uses astro, astro requries either bun or node to compile, you need one of them, on node without bun you'd need to swap the test file out for `jest` from npm but they are not required to build the site itself.

No matter what you would need bun or node, that is an intentional decision.

**Comment by trflynn89** [comment]
Of course the build scripts do. But it is not Ladybird's job to execute those scripts, and those scripts will continue to require `bun` or `node`.

**Comment by versecafe** [comment]
Astro cannot be built with Webkit, Gecko, or Blink it needs surrounding tooling that is outside the scope of the browser and making a new JS runtime on top of LibJS and then getting Astro, tailwind, and everything else to support it is outside of the scope of the project, No company currently makes both a browser JS engine and a widely support JS runtime.

**Comment by versecafe** [comment]
This is the same as how ladybird uses vcpkg + sh, bun serves for build tooling package management and scripting

**Comment by trflynn89** [comment]
Exactly which WHATWG spec takes an uncompiled website (in our case, Astro; in other cases, e.g. React apps) and then executes the build script for those sites?

**Comment by trflynn89** [comment]
That is not at all what you are asking for.

That spec is for webpages with an `<input type=file>` element to accept files from the user. It is *not* for the browser to load arbitrary build scripts and then execute them to build a website.

**Comment by versecafe** [comment]
If you go on the Ladybird discord this could be discussed in the VC
