### ISSUE TITLE
First link to Ladybird's website in the README still redirecting to dot dev website

### ISSUE THREAD

**Issue by CheewyOFF** [LadybirdBrowser/ladybird#575]
The first link in the README of the project redirect to an (apparently ?) older URL of the project's website : https://ladybird.dev. As a new user discovering the project from GitHub, I get a not so nice "We moved" blank page for a second before getting redirected. 

I understand that this as been done on purpose, but I think that the "main" link of the Github project to the website should be updated, at least for good measure.

**Comment by simonkrauter** [comment]
You are right, it needs to be replaced by ladybird.org.
Do you want to create a PR?

**Comment by CheewyOFF** [comment]
First time on Github, I guess this is perfect for learning :)

**Comment by simonkrauter** [comment]
> First time on Github, I guess this is perfect for learning :)

Exactly. Please take notice especially of the rules for the commit message, see https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md

**Comment by CheewyOFF** [comment]
I will, thank you very much

**Comment by ADKaster** [comment]
Closed with #577
