### ISSUE TITLE
How can I build Ladybird?

### ISSUE THREAD

**Issue by JoHenri** [LadybirdBrowser/ladybird#584]
I suppose this is a dumb question, but here goes.  I think this is a great project.  I'd like to build it and try it out.  I have Visual Studio Community edition and I have VS Code.  I downloaded the code but was unsure what to do with it.  Hope you can help and I apologize for my stupidity.  I've written lots of C, and C++, and now C# code.
thanks,
Joe

**Comment by ADKaster** [comment]
On Windows, the best option is to install WSL2, and use VsCode Remote + the plugins from the VsCodeConfiguration.md file in Documentation/

So...

1. install WSL2 (ubuntu or debian)
2. Install  ubuntu dependencies
3. configure vscode
4. ???
5. Profit

Steps 2 and 3 are in Documentation/BuildInstructionsLadybird.md

**Comment by ADKaster** [comment]
Make sure to clone it in your WSL2 home directory, the performance with the code cloned in your windows filesystem is terrible.

so `/home/me/ladybird` rather than `/mnt/c/Users/me/Projects/ladybird`

**Comment by ADKaster** [comment]
If you have any more questions, or ideas on how to improve our build docs to make this clearer to other windows users, please come chat in #build-problems on discord or open a docs PR :)
