### ISSUE TITLE
Subsequent-sibling combinator / display: inline-flex doesn't work right

### ISSUE THREAD

**Issue by simonkrauter** [LadybirdBrowser/ladybird#610]
Minimal test page:
```html
<!DOCTYPE html>
<html>
<style>
  * {
    border: 1px solid grey;
  }

  div > :not([hidden]) ~ :not([hidden]) {
    margin-top: 20px;
  }

  span {
    display: inline-flex;
    width: 180px;
    height: 64px;
    background: yellow;
  }
</style>
</head>
<body>
<div>
  <span>1</span>
  <span>2</span>
</div>
```

Screenshot Ladybird:
<img src="https://github.com/user-attachments/assets/6b1a716b-163c-4a36-b0a7-c28ddb6a813d" width="400"/>

Screenshot Chrome:
<img src="https://github.com/user-attachments/assets/5803e96e-9633-4712-8ae8-17b065888efe" width="400"/>

Reduction from https://ladybird.org.

<img src="https://github.com/user-attachments/assets/0e7318bc-0795-4410-ace9-18a4ebaaa607" width="400"/>

**Comment by dzfrias** [comment]
I don't think this is an issue with the subsequent sibling combinator. Changing the `display: inline-flex` to `display: inline-block` fixes the rendering. Or putting `border: 1px solid red` on the selector that involves the subsequent sibling combinator shows that it selects the correct element. 

I think it's an `display: inline-flex` issue.

**Comment by dzfrias** [comment]
This has been fixed!
