### ISSUE TITLE
Meta: ladybird.sh run does not quit the browser on ctrl+c on macOS

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#68]
After we refactored ladybird.sh run to use `open` to open the browser's app bundle, ctrl+c in the terminal that spawned the app no longer quits the app.

We should use the proper open flags or shell trickery to make sure that ctrl+c in the terminal actually quits the app instead of leaving it open.

**Comment by a4v2d4** [comment]
Confirming that this is fixed in main branch since PR #472 has been merged.
