### ISSUE TITLE
JXL support

### ISSUE THREAD

**Issue by RubenKelevra** [LadybirdBrowser/ladybird#683]
I've searched in the source code, and there seems to be test-cases for the JPEG-XL data format. But the browser itself doesn't load any JXL-files on the test-website.

https://jpegxl.info/test-page/

Is support still unfinished or is it currently broken?

**Comment by skyrising** [comment]
We have a home-grown JPEG-XL decoder, but it's incomplete. The images on that page happen to use features we don't support yet (Encoding VarDCT and animation).
The decoder will likely be replaced by libjxl soon-ish.

**Comment by LucasChollet** [comment]
The current decoder is the unfinished one that I developed from scratch for SerenityOS. It only supports a subset of lossless so you might want to test with the jxl-art, the success rate is better there.
I will open a PR to replace it with libjxl soon.

**Comment by RubenKelevra** [comment]
That's exciting to hear that the support will be improved. Thanks for the fast response. 

Quite cool actually, that you wrote your own decoder!

**Comment by RubenKelevra** [comment]
I've checked, it works great. Thanks @awesomekling!
