### ISSUE TITLE
[Discussion] IRC and XMPP support chat

### ISSUE THREAD

**Issue by sjehuda** [LadybirdBrowser/ladybird#708]
Greetings, everyone!

Please add official IRC or XMPP or both type of chats as an official communication arena.

I do not use any non-standard or centralized telecommunication means.

I do not even have a telephone.

Schimon

**Comment by circl-lastname** [comment]
I understand your dislike of Discord, however Andreas has reiterated that:

> And we're perfectly happy using proprietary services like GitHub and Discord as long as they make our work easier and more enjoyable. We recently evaluated a number of alternatives, and found that they all introduced more friction than we were comfortable with.

[Source](https://news.ycombinator.com/item?id=40855179)

And that he's not interested in changing it unless there is a real, pragmatic, practical, or technical reason.

**Comment by sjehuda** [comment]
Thank you.

Please convey him that I develop chat bots and software for XMPP, and I also work on a general purpose [moderation bot](https://git.xmpp-it.net/sch/KaikOut).

I am currently working on an XMPP-based social bookmarks service, so the development of bots is halted for a few weeks.

Please convey to Andreas that I am willing to bargain with him for an XMPP groupchat, in return for a bot that he would want ot have, if at all.

Closing.
