### ISSUE TITLE
[Discussion] Promoting Ladybird in my Syndication Feed Reader (Userscript)

### ISSUE THREAD

**Issue by sjehuda** [LadybirdBrowser/ladybird#710]
Greetings!

I have heard of Ladybird, several months ago, and I have decided to add references to it in [my project](https://greasyfork.org/en/scripts/465932-newspaper-html-feed-reader) ([a JS-based syndication feed reader](https://openuserjs.org/scripts/sjehuda/Newspaper)). My projects occupies a whole view-port, so I have realized I will use it to promote things I want

To see the text, you need to
- install the userscript,
-  open an Atom or RSS feed,
-  scroll to the bottom,
- click on "Help & Information",
- click on "What Are The Alternatives?"

And you will see this:
```
    <h3>🐦 <a href="https://ladybird.org/">Ladybird</a></h3>
    <h3>A New Cross Platform Browser Project.</h3>
    <p>The Ladybird browser came to life on July 4th; it was originally a headless mode of LibWeb (previously LibHTML) and is also featuring a Qt GUI for the LibWeb browser engine. Ladybird was intended to be a debugging tool for people to remain in Linux while working on LibWeb if they wanted to. Two months later, Ladybird has became a browser in its own right.</p>
    <p>At this point, we might as well tweak the scope from “browser engine for SerenityOS” to “cross-platform browser engine” and build something that many more people could potentially have use for some day. :^)</p>
```

In addition to it, there is a dynamic link which changes upon loading the script, and one of the random links is this:
```
    { // ladybird
      'text' : 'Get Ladybird',
      'link' : 'https://ladybird.org/',
      'title' : 'A New Cross Platform Browser Project',
    },
```

Please inform me if you have any requests to change something or even add.

This is the footer of each syndication feed page: 
![2024-07-19-182439_1920x1080_scrot](https://github.com/user-attachments/assets/c7bf48fd-3287-44f6-8d7e-31feefb6fdad)

The link "Get Ladybird" is random. If you want, I wiil make it constant, so it be sujected to receives more attention.

**Comment by AtkinsSJ** [comment]
Hi! Sorry for the long wait for a response. It's cool of you to add a link to Ladybird, but I really wouldn't recommend the general public use it until we do a proper release in a couple of years. It's just not stable or complete enough for normal use.

**Comment by sjehuda** [comment]
Sure.

Please do inform me when ever you want.

I also intend to create a desktop version of that Greasemonkey script,
including the articles that are already attached to the script; and due
to the context of syndication, it would be good to have feed and xslt
support in Ladybird when we highlight Ladybird.

---

It has turned out, that the removal of the RSS button has been turning
against those who have done that shenanigan.

https://openrss.org/blog/browsers-should-bring-back-the-rss-button

I would recommend you to consider that these four companies are aware
of their mistake, and are aware of my software (at least a couple of
them know of it), which might make my software lesser relevant, and
consequebtly, we might lose this propaganda opportunity.
