### ISSUE TITLE
Gemini and Gopher support

### ISSUE THREAD

**Issue by sjehuda** [LadybirdBrowser/ladybird#711]

**Comment by circl-lastname** [comment]
Gemini support was removed in f2fd8fc92898b5312bd7bc787cc8221f5650ce65 due to lack of support and interest

**Comment by sjehuda** [comment]
It would be good to me if support be resored.

I am working on a news chat bot for XMPP which works well with HTTP and I intend to add support to Gopher and Gemini, yet non of the available modules appear to satisfy my needs.

If Ladybird has a "headless" mode, so called, then it would greately be useful to my bot.

This is a link to my bot https://git.xmpp-it.net/sch/Slixfeed and it can serve hundreds and probably even thousands of chats at the same time.

**Comment by awesomekling** [comment]
The main focus of Ladybird is to support the same widely-adopted standards that other major browsers support. We're building a browser for the web, not a showcase for niche technologies :)

**Comment by sjehuda** [comment]
I would argue and say that we, that is people, are deciding the standards, yet the problem is that so called "standards" are being foisted on us.

Gopher was an integrated part of Mozilla products and so was RSS.

Is Gopher still relevant? Yes.
Is RSS still relevant? [Certainly](https://openuserjs.org/scripts/sjehuda/Newspaper)!

The fact that big money browsers with big interests from advertising to spy industries, including government intelligence, are attempting to set the standards, does not mean that these are real standards, nor acceptable, nor appropriate.

Hence, I think that Gemini and Gopher are crutial.

I use Lagrange every day, and after a couple of months, I am *smiling* each session I have with Lagrange.

I am really smiling, because of the comfort.

Corporations do not smile, humans do.

**Comment by sjehuda** [comment]
By the way, adding Gemini support is probably the first Falkon extension that I will publish.

**Comment by AtkinsSJ** [comment]
I don't think we're ruling out Gopher etc. It's just that we're a small team with a tight deadline for a usable alpha version in 2026, so we have to prioritise things.

- If a web browser doesn't implement Gopher, or Gemini, or RSS, it's still a functional browser to most people.
- If a web browser doesn't implement all the DOM APIs, or common media codecs, or CSS properties, or if it crashes and bugs out, then it's no good to anybody. 

So, we have to focus on getting it to work well with the web that people use, first.

**Comment by circl-lastname** [comment]
> I would argue and say that we, that is people, are deciding the standards, yet the problem is that so called "standards" are being foisted on us.

In the case of this project, the standards are ultimately decided by the W3C, WHATWG, and ECMA. This project's current single goal is implementing a client for the Web as laid out by them, however:

> The fact that big money browsers with big interests from advertising to spy industries, including government intelligence, are attempting to set the standards, does not mean that these are real standards, nor acceptable, nor appropriate.

Yes, it is possible that a standard which blatantly violates the user's privacy were accepted by W3C or WHATWG, but in that case the maintainers of Ladybird can simply choose to not implement it. *That* is the advantage of no funding or control from the advertising industry.

**Comment by sjehuda** [comment]
Understood. I am following this matter. Thank you!

**Comment by sjehuda** [comment]
I would be glad to have Gemini support, because my main browser is currently Lagrange, and as I am more involved with Gemini, including developing software of Gemini, I would be glad to test LadyBord with Gemini.

My journal.

gemini://woodpeckersnest.space/~schapps/journal/

My publication project which supports XMPP, Gemini, and HTTP.

https://git.xmpp-it.net/sch/Rivista

**Comment by sjehuda** [comment]
Please. Restore Gemini.

I rarely browse HTTP, aside from projects that I develop.

Most of my oresent activity is over Gemini.
