### ISSUE TITLE
CTRL+C should exit js shell

### ISSUE THREAD

**Issue by guest271314** [LadybirdBrowser/ladybird#743]
Typically `CTRL`+`C` exits a JavaScript shell. `js` does not exit, only `exit()` exits.

Compare `js` behavior to V8's `d8`, Mozilla's `spidermonkey`, `node`, `deno`, `bun`, `qjs`, `tjs`

```
$ js
> ^C
> ^C
> ^C
> ^C
> ^C
> ^C
> ^C
> ^C
> exit()
```

```
~/.jsvu/bin/v8
V8 version 12.8.346
d8> ^C
```

```
$ spidermonkey
js> 
```

```
$ deno
Deno 1.45.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> 
press ctrl+c again to exit
> 
```

```
$ node
Welcome to Node.js v23.0.0-nightly2024071586415e4688.
Type ".help" for more information.
> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 
```

```
$ qjs
QuickJS-ng - Type ".help" for help
qjs > 
(Press Ctrl-C again to quit)
qjs > 
```

```
$ bun repl
Welcome to Bun v1.1.20
Type ".help" for more information.
[!] Please note that the REPL implementation is still experimental!
    Don't consider it to be representative of the stability or behavior of Bun overall.
> 
```

```
$ tjs
Welcome to txiki.js — The tiny JavaScript runtime
Type "\h" for help
> 
(Press Ctrl-C again to quit)
> 
```

**Comment by kemzeb** [comment]
After looking [here](https://github.com/LadybirdBrowser/ladybird/blob/8affa377fb15a2d0e2471c370aca042642bd2f52/Userland/Utilities/js.cpp#L597C1-L601C12), it appears we should already honor Ctrl+C. After some manual tests, however, it looks like this signal handler isn't called for some reason (running it on a WSL machine). My best guess so far is that the we replace the signal handler for `SIGINT` with some other handler somewhere after we set it here.

One workaround I see to exit the repl quickly is to use Ctrl+D.

**Comment by alimpfard** [comment]
^D exits the REPL, as in basically every good shell in existence.
^C simply cancels the current line input; @kemzeb I'm not sure if/whether this works in your terminal emulator - it should, if your emulator supports raw mode (if you're seeing the `^C` shown in OP's report, it works).

We can implement the "hit ^C twice to exit" behaviour, but that's not something I'm personally familiar with.
