### ISSUE TITLE
LibWeb/CSS: overflow: hidden does not properly cut off elements with a rotation applied

### ISSUE THREAD

**Issue by samfry13** [LadybirdBrowser/ladybird#755]
A container with `overflow: hidden` doesn't properly cut off elements with a `transform` rotation applied.

Example:
```html
<style>
    .container {
        width: 500px;
        height: 500px;
        background: blue;
        position: relative;
        overflow: hidden;
    }

    .item {
        content: " ";
        width: 100%;
        height: 300px;
        background: red;
        position: absolute;
        bottom: 20%;
        left: 30%;
        transform: rotateZ(-12deg);
    }
</style>

<div class="container">
    <div class="item"></div>
</div>
```

| Ladybird | Arc (Chromium) |
| - | - |
| ![Screenshot 2024-07-22 120854](https://github.com/user-attachments/assets/31fa6ec4-dd12-4185-9995-470166cd27aa) | ![Screenshot 2024-07-22 120915](https://github.com/user-attachments/assets/0463314d-deed-49fa-a727-596b7f8047ee) |

**Comment by kalenikaliaksandr** [comment]
Fixed by https://github.com/LadybirdBrowser/ladybird/pull/917
