### ISSUE TITLE
Saving screenshot fails if Downloads directory doesn't exist

### ISSUE THREAD

**Issue by doctortheemh** [LadybirdBrowser/ladybird#780]
"Take Visible Screenshot" or "Take Full Screenshot", saving screenshot fails with error: "open: No such file or directory (errno=2)". Relevant OS details: Debian on WSL2. 

Looks like relevant code might be in `ViewImplementation.cpp:484` and `StandardPaths.cpp:61`. I did not have a ~/Downloads folder, and adding one fixes the behavior.

**Comment by AtkinsSJ** [comment]
Seems reasonable to create that directory if it doesn't exist.

**Comment by ADKaster** [comment]
There should be an API in either Core::System or LibFileSystem that can make a directory with parents that could be called before trying to write the file to the downloads folder.

**Comment by trflynn89** [comment]
What do other browsers do on your system? Do they save to your home folder, or tmp folder, or ...? We can just mimic what that. I sorta don't think we have any business creating a Downloads folder.

**Comment by dudleyinnocent** [comment]
I suggest refraining from creating directories on a system as we are not completely sure of the permission landscape at all times. Perhaps asking, per screenshot, the user where should it be saved or dumping the screenshot onto the clipboard after notifying the user of the issue would be best?

**Comment by loknath2002** [comment]
> What do other browsers do on your system? Do they save to your home folder, or tmp folder, or ...? We can just mimic that. I sorta don't think we have any business creating a Downloads folder.
Firefox(129.0) on Windows 11(22H2) creates a directory in case of non-user folder. ex D:\TestDownloadFolder

Directory Creation probably isn't straight forward as different OS handle it differently and permission landscape is quite different too. In case of Directories present under %UserProfile% for example **Downloads**, On windows platform these folders are also part of certain registry entries which could also have unintended side effects.

We probably need to deal with some folders rather as special cases compared to others. This will also help in emerging a better permission handling strategies too.

**Comment by cnyrr** [comment]
> home folder, or tmp folder

Isn't it a better idea to try creating the folder first implicitly, and prompt user to pick a location as fallback. Downloading a file into temp folder defeats the purpose of it.

If my memory serves me right, browsers used to make the users always pick between "Open" and "Save" unless user set a default in the past. Clicking "Open" saved the file in the temp - as expected for "temporary" files -, while "save" prompted the user to pick/change the location.

**Comment by saurabh123321** [comment]
On chrome (windows OS), if we take a screen shot, it only saves it on clipboard, it doesn't pops up anything saying, do I want to dump it to downloads or any other folder, can we not make it in sync with this?

**Comment by olliehcrook** [comment]
What are the exact steps to reproduce this? I am trying to get the same error on a linux VM with ~/Downloads removed and have so far failed to reproduce.

**Comment by Laura-Braun** [comment]
@doctortheemh  sorry if I'm missing something obvious but I don't see the option to take screenshot or save it anywhere. can you share how you got it.

![image](https://github.com/user-attachments/assets/c23b39a8-442e-4223-a692-61bbae7e22cf)

**Comment by circl-lastname** [comment]
What version of Ladybird is that?

**Comment by trflynn89** [comment]
You've right-clicked on an image, which we've apparently not added the screenshot actions on. Right-click somewhere else, like on some text, and you'll see these:
![Screenshot_20240818_131800](https://github.com/user-attachments/assets/5cfb8678-aa1e-4195-8789-560dfbdb3ee4)

**Comment by olliehcrook** [comment]
![err_msg_missing_downloads](https://github.com/user-attachments/assets/e30c47e9-d8d2-4165-a3bb-efa76abe9784)
This is the current dialog we get when ~/Downloads is not present. Perhaps an option to set downloads directory would be appropriate for systems without the default present?

**Comment by som-cs** [comment]
Can't we go like, look for downloads folder -> if not present look for pictures folder -> if not present save in home (~) folder. If you do not have a ~ then this warning will make sense and also we can give option to set it from the setting if the user wants. then whatever folder the user have selected and he deletes that folder after we just create that folder and if the user blows the entire directory tree out of existence we can just revert back to default process. If no one is working on this i would like to take this up.

**Comment by shinarit** [comment]
Since this looks like a highly complex issue of protocols, with potentially complex solutions of lookups, might I suggest removing the good first issue label?

From a user perspective, silently trying to create the directory sounds like the solution I would expect from a program that wants to save something somewhere I set for it (or defaulted to something reasonable). If that's not successful, then we need an error message.

**Comment by circl-lastname** [comment]
I believe just creating the Downloads directory with Core::Directory::ensure will work fine in the 99% of cases. An option to change the save location can be added later
