### ISSUE TITLE
better dev tools (maybe use eruda as a start)

### ISSUE THREAD

**Issue by jogibear9988** [LadybirdBrowser/ladybird#806]
hello,

today I found https://eruda.liriliri.io/

maybe it would be possible to include the possibility to inject this into the page, as long as ladybird devtools are not yet up to the chrome/firefox/safari ones?

**Comment by AtkinsSJ** [comment]
Hi!

Eruda is very impressive, but it currently just crashes Ladybird, so it's not usable. :sweat_smile: I expect it's using a lot of APIs we don't support yet.

Support for that will improve over time, but I think if we want good dev tools, it's better to directly work on improving them instead.
