### ISSUE TITLE
Transparent accounting?

### ISSUE THREAD

**Issue by Kreyren** [LadybirdBrowser/ladybird#820]
From your website i got the impression that you want to have a non-profit structure that is funded by the community to remain independent -> Make a transparent accounting so that it's easily verifiable and is a constant safeguard against this e.g. opencollective?

**Comment by awesomekling** [comment]
The Ladybird Browser Initiative will publish its own financial reports at a regular interval, with maximum transparency.

Closing, as this is not a bug report :)

**Comment by Kreyren** [comment]
cool :+1:
