### ISSUE TITLE
LibWeb: Make the WPT encoding/legacy-mb-* tests pass

### ISSUE THREAD

**Issue by awesomekling** [LadybirdBrowser/ladybird#824]
These tests make up a huge part of the WPT score, so it would be nice to get them out of the way.

I'm talking specifically about:
- encoding/legacy-mb-japanese
- encoding/legacy-mb-korean
- encoding/legacy-mb-schinese
- encoding/legacy-mb-tchinese

From my understanding, we need to implement form submission with encodings other than UTF-8.

## Funding

- We're using [Polar.sh](https://polar.sh/SerenityOS) to allow folks to offer a reward for completing this issue.
- The contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/LadybirdBrowser/ladybird/issues/824">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/LadybirdBrowser/ladybird/issues/824/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/LadybirdBrowser/ladybird/issues/824/pledge.svg">
</picture>
</a>

**Comment by tcl3** [comment]
Fixed by #975

**Comment by awesomekling** [comment]
Thank you @BenJilks for contributing to close this issue! ⭐

The rewards from this issue, totaling $300, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
