### ISSUE TITLE
Trying to get ladybird to work how i like

### ISSUE THREAD

**Issue by Kreyren** [LadybirdBrowser/ladybird#852]
Hey, for context i had a discussion with other devs about this project and this kinda feels like an annoying thing to do, but i am too curious about the outcome to not try so i apologize in advance for being the eqvivalent of really annoying and impatient supervisor at a tech company:

Ladybird seems like a very interesting project as the closest i can get to anything close to same in ideology and dependency on 3rd party is using schizofox which still depends on mozilla and their apparent mismanagement of funds and business to depend on google for their ability to function and trying to unsuccessfully convert on a more sustainable model while annoying the fuck out of me with ads -> Any chance to get an objectively better web browser that i can already use now despite it being in development?

Currently i am doing this firefox config https://github.com/NiXium-org/NiXium/blob/ec5a7e8b4f113de4cbd295221d6265e52454d629/src/nixos/users/kreyren/home/modules/web-browsers/firefox/firefox.nix which i eventually want to merge in shizofox to well.. at least make the internet a bit more usable.. Getting somewhat closer or beyond it would be nice.

Cross-referencing: https://github.com/NiXium-org/NiXium/issues/83

**Comment by ADKaster** [comment]
Is there a question here? I'm not sure I understand what the feature request or issue is you're trying to report.

> Any chance to get an objectively better web browser that i can already use now despite it being in development?

If this is the question you're asking... yes? In two years, when we release our first Alpha for developers and early adopters.
