### ISSUE TITLE
Downloads directory -- when to init if does not exist?

### ISSUE THREAD

**Issue by ChromiteExabyte** [LadybirdBrowser/ladybird#854]
[Saving screenshot fails if Downloads directory doesn't exist Issue #780](https://github.com/LadybirdBrowser/ladybird/issues/780)

^ Issue #780 is the base issue; below is aprox ViewImplementation.cpp, line 485 

```C++

ErrorOr<void> ViewImplementation::take_screenshot(ScreenshotType type)
{
    Gfx::ShareableBitmap bitmap;

    switch (type) {
    case ScreenshotType::Visible:
        if (auto* visible_bitmap = m_client_state.has_usable_bitmap ? m_client_state.front_bitmap.bitmap.ptr() : m_backup_bitmap.ptr())
            bitmap = visible_bitmap->to_shareable_bitmap();
        break;
    case ScreenshotType::Full:
        bitmap = client().take_document_screenshot();
        break;
    }

    if (!bitmap.is_valid())
        return Error::from_string_view("Failed to take a screenshot of the current tab"sv);

    LexicalPath path { Core::StandardPaths::downloads_directory() };
    path = path.append(TRY(Core::DateTime::now().to_string("screenshot-%Y-%m-%d-%H-%M-%S.png"sv)));

    //  this line is new
    TRY(Core::System::make_directory(Core::StandardPaths::downloads_directory().string(), 0755));
    //^^^^^^
    // Also, this line might not work on mac / windows ? 

    auto encoded = TRY(Gfx::PNGWriter::encode(*bitmap.bitmap()));

    auto screenshot_file = TRY(Core::File::open(path.string(), Core::File::OpenMode::Write));
    TRY(screenshot_file->write_until_depleted(encoded));

    return {};
}
));
```
Having the above line fixes the error by making a directory (I hope),
but, 
does it make more sense to handle the case of missing / broken Downloads filesystem paths in  elsewhere in the scope, like in System.cpp? Please let me know if this is or isn't within the contributing guidelines, I am new to contributing, thank you.

**Comment by circl-lastname** [comment]
It would work. Though no other standard_path does that, it should be fine.
This will work on Mac/Windows because Macs are Unix-like and we don't support Windows yet :^)

Alternatively you can do Core::Directory::ensure_directory before it tries to save a screenshot in the Qt UI

**Comment by circl-lastname** [comment]
Also, make you should use Core::Directory::create with CreateDirectories::Yes, so that it doesn't fail if it already exists
