### ISSUE TITLE
HTTP redirect error with --enable-http-cache on Github Pages

### ISSUE THREAD

**Issue by dotnetCarpenter** [LadybirdBrowser/ladybird#863]
Using Ladybird 89a4fa4d24 and `--enable-http-cache`. I can not trigger the error without the cache flag.

It seems that the 301 redirect page is cached and served by the HTTP-cache instead of redirecting.

I believe this to be a regression but I have not done a `git bisect`.

### Steps to reproduce:

1. ./Build/ladybird/bin/Ladybird --enable-http-cache https://maggie-borger.com/
2. Click on the "Works" link, in the menu to the left (this will navigate to https://maggie-borger.com/works)
3. If you do not get a 301, then click on "Works" again.

```
55528.200 WebContent(177899): Web::EventHandler: Clicking on a link to https://maggie-borger.com/works
55528.200 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/works
55528.252 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/works/
55528.368 WebContent(177899): HTTP CACHE HIT! https://maggie-borger.com/_astro/biography.B86vKf1S.css
55528.368 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/works.DiBcDSQd.css
55528.400 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/borger-survival.C49-7onS_Z29t3Vd.webp
55528.428 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/broken.DeVRfEAw_2qtNyb.webp
55528.428 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/seal.aGj0trKj_Z1PRLvg.webp
55528.428 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/liferecline.TQSiwyzU_1REruG.webp
55528.432 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/tashstrawberyrose.DMHY5h42_Z2cqdY4.webp
55528.448 WebContent(177899): ResourceLoader: Failed load of: "https://maggie-borger.com/works/favicon.svg", Error: Load failed: 404, Duration: 84ms
55528.480 WebContent(177899): HTTP CACHE MISS! https://maggie-borger.com/_astro/macaron640.Bv5LZCbq_uQPr0.webp
55528.496 WebContent(177899): HTTP CACHE HIT! https://maggie-borger.com/favicon.ico
55530.480 WebContent(177899): Web::EventHandler: Clicking on a link to https://maggie-borger.com/works
55530.480 WebContent(177899): HTTP CACHE HIT! https://maggie-borger.com/works
55530.516 WebContent(177899): HTTP CACHE HIT! https://maggie-borger.com/favicon.ico
```

![Screenshot of Ladybird getting an 301](https://github.com/user-attachments/assets/77df7f37-7e88-44d4-b85a-7f256424fe5b)

### Expected behavior

Ladybird should follow the HTTP redirect `Location` header.

Response headers:
```
Request URL:
https://maggie-borger.com/works
Request Method:
GET
Status Code:
301 Moved Permanently
Remote Address:
185.199.111.153:443
Referrer Policy:
strict-origin-when-cross-origin
Accept-Ranges:
bytes
Access-Control-Allow-Origin:
*
Age:
20
Cache-Control:
max-age=600
Content-Length:
162
Content-Type:
text/html
Date:
Sat, 27 Jul 2024 15:08:39 GMT
Expires:
Sat, 27 Jul 2024 15:18:18 GMT
Location:
https://maggie-borger.com/works/
Server:
GitHub.com
Vary:
Accept-Encoding
Via:
1.1 varnish
X-Cache:
HIT
X-Cache-Hits:
1
X-Fastly-Request-Id:
5c155f00a09ff243e8cb538d43f9ddcea8de4e42
X-Github-Request-Id:
1012:8F220:393C871:3AC527F:66A50D62
X-Proxy-Cache:
MISS
X-Served-By:
cache-cph2320057-CPH
X-Timer:
S1722092919.115310,VS0,VE1
```

**Comment by sideshowbarker** [comment]
> I believe this to be a regression but I have not done a `git bisect`.

I tested the repro steps with https://github.com/LadybirdBrowser/ladybird/commit/47169db452 the parent of the change which added `--enable-http-cache`, https://github.com/LadybirdBrowser/ladybird/commit/a3c8e60710, and with that I don’t get 301 page shown, but instead Ladybird follows the redirect as expected. But building with https://github.com/LadybirdBrowser/ladybird/commit/a3c8e60710 commit, I do get the 301 page shown, and Ladybird does not follow the redirect as expected.

So I guess the https://github.com/LadybirdBrowser/ladybird/commit/a3c8e60710  `--enable-http-cache` change is what regressed the redirect behavior?
