### ISSUE TITLE
Small tweak to 'build ladybird' install / run steps

### ISSUE THREAD

**Issue by htx80nerd** [LadybirdBrowser/ladybird#871]
"Build Prerequisites" explains what commands to do to get ready. 

The next section is "Build steps : Using ladybird.sh"

The first step is running ladybird.sh

However at this point none of the prior steps would have placed ladybird.sh on the users system.

Please add these steps 

`$ git clone https://github.com/LadybirdBrowser/ladybird/`
`cd ladybird`
`cd Meta`

**Comment by alimpfard** [comment]
There's no reason to `cd Meta`, the commands in the "Using ladybird.sh" section invoke them from the toplevel dir:
<https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/BuildInstructionsLadybird.md?plain=1#L161-L169>
```bash
# From /path/to/ladybird
./Meta/ladybird.sh run ladybird
```

As for the `git clone` step, I would expect anyone trying to build a browser from git to have cloned the repository already?

**Comment by trflynn89** [comment]
Agreed, see https://github.com/LadybirdBrowser/ladybird/issues/430#issuecomment-2211451171 for previous discussion.
