### ISSUE TITLE
Contribution: Discord server links expired

### ISSUE THREAD

**Issue by guisoaresdev** [LadybirdBrowser/ladybird#881]
All the Discord Server Links are expired, I would like to be able to join the community.

Ocurrencies:
https://github.com/LadybirdBrowser/ladybird/blob/master/CONTRIBUTING.md#communication
https://github.com/LadybirdBrowser/ladybird/blob/master/README.md#get-in-touch-and-participate
https://ladybird.org/#gi (Img: [Screenshot_1](https://github.com/user-attachments/assets/4653d033-3d1d-40ab-874d-4d4aa3340af4))

**Comment by circl-lastname** [comment]
Cannot reproduce

**Comment by AtkinsSJ** [comment]
Yeah the link isn't expired for me either. Maybe contact Discord about it.

**Comment by guisoaresdev** [comment]
> Cannot reproduce, links are working as expected on my side Have you tried copying them into the Discord (+) -> Join a server menu? Perhaps you have been blocked in some way?

This worked
