### ISSUE TITLE
Mixed question, regarding qt6,

### ISSUE THREAD

**Issue by FrostKnight** [LadybirdBrowser/ladybird#882]
Will you be making portable zips of this when you are done and will they need qt6 installed on system to be executed?

Also, is qt6 the only qt you plan to support? I don't know what you will say, but should I assume you won't support qt5 in any form?

If thats the case, just curious.

**Comment by bbb651** [comment]
Not a core developer but I don't think there'll be qt5 support, the last minor version released in 2020 and it's already way [past end of support for non-commercial versions](https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders) (26/5/2023) and multiple chromes are already a bit of a problem to maintain.

Also generally there are no plans (other than the long term alpha release date goal), things might change, e.g. maybe the chrome will be web based at some point like firefox.  (try the `/plan` command if you're on the discord)

**Comment by circl-lastname** [comment]
Qt6 is present on all distributions, even on Debian. I don't see a reason to support Qt5

**Comment by FrostKnight** [comment]
> Not a core developer but I don't think there'll be qt5 support, the last minor version released in 2020 and it's already way [past end of support for non-commercial versions](https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders) (26/5/2023) and multiple chromes are already a bit of a problem to maintain.
> 
> Also generally there are no plans (other than the long term alpha release date goal), things might change, e.g. maybe the chrome will be web based at some point like firefox. (try the `/plan` command if you're on the discord)

Hmm... well that does make sense I suppose.

There is also a toolkit called FLTK as well I have interest in too.

It would be interesting to have an FLTK interface as an option in addition to qt6, just my two cents.

FLTK is a lighter interface is why. uses much less resources.

**Comment by ADKaster** [comment]
We're going to try to keep the number of supported chromes to a minimum for the alpha release, due to maintainer time concerns. Of course folks will be free to package their own UI chromes, it's FOSS after all. In this repo we very likely won't be supporting Qt5. Qt6 and AppKit are already going to be interesting to support for the core contributor size.

**Comment by ADKaster** [comment]
> Will you be making portable zips of this when you are done and will they need qt6 installed on system to be executed?

It's a bit early to ask this question, the first alpha is planned for 2026. But in general, I would prefer this repo be responsible for a flatpak and a macOS app bundle, and let any other distribution type be up to distros.

**Comment by FrostKnight** [comment]
> We're going to try to keep the number of supported chromes to a minimum for the alpha release, due to maintainer time concerns. Of course folks will be free to package their own UI chromes, it's FOSS after all. In this repo we very likely won't be supporting Qt5. Qt6 and AppKit are already going to be interesting to support for the core contributor size.

Righto, maybe when you have stable releases this will change? Or if you have users willing to devote time, etc... I would like to, but I have not the skills to do so.

first alpha 2026...hmm.

Btw, the fewer dependencies to compile, the better.  flatpak should probably only be required for making a flatpak version of it but nothing else.

being able to compile using ./configure make and make install would be my preference personally. 

;)

**Comment by ADKaster** [comment]
> being able to compile using ./configure make and make install would be my preference personally

Best you're going to get for that is `cmake --preset Release && cmake --build --preset Release && cmake --install Build/ladybird-release`. It's not 2003 anymore, hand jamming m4 macros and make files is madness.

> Btw, the fewer dependencies to compile, the better.

That's great until you realize that we have a ton of features to support in order to renderer the modem web and we don't have time to make rock solid implementations that are fully tested, audited, hardened, fuzzed, and security-approved. That's what FOSS is for.

**Comment by ADKaster** [comment]
Shooting the breeze aside, I think this question is pretty much answered :). 

Will we make portable zips? Probably not, flatpak is in the table though.
Will it require Qt6? On Linux, probably, unless we move to a GTK chrome
Will we support Qt5? Not in this repository

**Comment by FrostKnight** [comment]
> Shooting the breeze aside, I think this question is pretty much answered :).
> 
> Will we make portable zips? Probably not, flatpak is in the table though. Will it require Qt6? On Linux, probably, unless we move to a GTK chrome Will we support Qt5? Not in this repository

Fair enough, 

> > being able to compile using ./configure make and make install would be my preference personally
> 
> Best you're going to get for that is `cmake --preset Release && cmake --build --preset Release && cmake --install Build/ladybird-release`. It's not 2003 anymore, hand jamming m4 macros and make files is madness.
> 
> > Btw, the fewer dependencies to compile, the better.
> 
> That's great until you realize that we have a ton of features to support in order to renderer the modem web and we don't have time to make rock solid implementations that are fully tested, audited, hardened, fuzzed, and security-approved. That's what FOSS is for.

Maybe I should rephrase what I said then... the fewer *required dependencies the better* 

Btw, I had meant portable zips, because, firefox devs have that.  Although, it doesn't mean ladybird needs them.

But yeah, anyways, appreciate the responses.
