### ISSUE TITLE
[proposal] Use and, or and not everywhere in the code, instead of &&, || and !

### ISSUE THREAD

**Issue by paaspaas00** [LadybirdBrowser/ladybird#919]
So apparently the C++ standard allows use of **and**, **not** and **or** as alternative for the well-known &&, || and ! keywords (I know, 
I didn't know either).
See this https://en.cppreference.com/w/cpp/language/operator_alternative

Using them project wide in if statements would make the code much more readable at a glance and make it less prone to stupid logic errors

**Comment by AtkinsSJ** [comment]
> Using them project wide in if statements would make the code much more readable at a glance and make it less prone to stupid logic errors

[Citation needed]

**Comment by gmta** [comment]
`&&`, `||` and `!` are used in pretty much every C-like language. I'm not convinced changing that would improve readability.

**Comment by paaspaas00** [comment]
I think that reading for instance condition1 and condition2 is more readable (at a glance) than condition1 && condition 2, especially when it is a complex expression with multiple logic subconditions. Especially when reading !condition, where the ! may not be seen easily and missed. 

These are mistakes that sometimes occurred to me so improving at-a-glance readability when going thru the code may benefit everyone I think. 

Personally, I think those alternative keywords are much more readable, being exactly spelled like the English words and enabling people to skim thru the text at the same speed and at the same understanding level as a page of English text.

**Comment by circl-lastname** [comment]
In my experience logical errors or misunderstandings are caused by a complex set of logical operations, such as, for example
```
a && (b || (c != d))
```
I don't think changing that to
```
a and (b or (c != d))
```
would improve readability

**Comment by Lampe2020** [comment]
In PHP both are allowed too, and there the word-shape ones have lower binding priority than the special symbol equivalents, though I use both of them mostly interchangeably. And I cannot say that one or the other would be easier to read. And I do also sometimes catch myself trying to use the special symbol ones in Python, where only the word-shaped ones exist.   
I would actually argue that the word-shaped ones are a tad more difficult to visually parse with more conservative colour highlighting, as variables and operators that way melt together to just a row of words if the kind of symbols used isn't distinct.   
Just my comment on this, I know this has been decided long ago.
