### ISSUE TITLE
IPv6 address servers do not work

### ISSUE THREAD

**Issue by RubenKelevra** [LadybirdBrowser/ladybird#941]
I'm using Ladybird 936b76f36e8.

I tried to open a website via IPv6 address, but Ladybird seems to be unable to open such addresses at the moment.

### Log

```
86726.596 RequestServer(222308:222313): ConnectionCache: Connection to http://[fd7a:115c:a1e0:ab12:4843:cd96:627d:d88]:8123/ failed: Name or service not known
86726.596 RequestServer(222308:222313): Request with a null socket finished for URL http://[fd7a:115c:a1e0:ab12:4843:cd96:627d:d88]:8123/
86726.596 WebContent(222318): ResourceLoader: Failed load of: "http://[fd7a:115c:a1e0:ab12:4843:cd96:627d:d88]:8123/", Error: Load failed, Duration: 14ms
```

### Screenshot

![Screenshot_20240803_082932](https://github.com/user-attachments/assets/175c481c-b7f0-4d4d-9864-29ea6377799c)

**Comment by circl-lastname** [comment]
Have you tried without the `[`? Should that be a valid character in an IPv6 address?

**Comment by RubenKelevra** [comment]
I forgot to mention, this obviously works fine in Firefox and this IPv6 is on my VPN network. So it won't work for anyone else trying this out either (as this is a private, non-routeable IP-Address), but that's not related to my issue.

**Comment by circl-lastname** [comment]
It looks like Ladybird is parsing this as a domain name instead of IPv6 address, despite f0ec104131ac1ef3b21d2187559f2c48ccfed5c8

**Comment by xlmnxp** [comment]
@RubenKelevra @circl-lastname I will look into this issue

**Comment by xlmnxp** [comment]
I discontinue working on this project, I will not contribute on this issue

**Comment by guilherme-puida** [comment]
I'm not able to reproduce this as of 43a07a0fde. I'm able to access my webserver via its IPv6 address directly.

![image](https://github.com/user-attachments/assets/beb18b9a-0ad6-4d32-8525-eb8b8798fcae)

**Comment by ChaseKnowlden** [comment]
Can we close this issue then?

**Comment by RubenKelevra** [comment]
I've checked with 34261e54901 and the bug is fixed. Thanks!
