### ISSUE TITLE
IPv6 address will be converted to Punycode

### ISSUE THREAD

**Issue by RubenKelevra** [LadybirdBrowser/ladybird#942]
I'm using Ladybird https://github.com/LadybirdBrowser/ladybird/commit/936b76f36e87a6d4cf267c15c95786ef677515fc.

While testing and discovering this bug (#941) I noticed that if I paste an IPv6-Address into the address bar with a port definition and `[` and `]` around the IPv6, that the address bar will momentarily convert the `[` and `]` characters erroneously to punycode.

As soon as you hit enter, the characters are correctly displayed as `[` and `]`

I thought that should probably be fixed. :)

![Screenshot_20240803_083000](https://github.com/user-attachments/assets/b6622243-f9cb-41ac-9467-b5b887b8a211)

**Comment by circl-lastname** [comment]
Is issue #941 the same as this one?

**Comment by RubenKelevra** [comment]
@circl-lastname nope. #941 is about connectivity issues to IPv6 addresses. This one is just about cosmetics if you paste an IPv6 address into the address bar.

**Comment by circl-lastname** [comment]
Have you tried an IPv6 address which does not use the `[]` notation? It seems like it causes the RequestServer to interpret it as a domain and attempt to look it up

**Comment by RubenKelevra** [comment]
Why would I? This would violate the URI standard RFC 3986, as:

> A host identified by an Internet Protocol literal address, version 6 [[RFC3513](https://datatracker.ietf.org/doc/html/rfc3513)] or later, is distinguished by enclosing the IP literal within square brackets ("[" and "]").

[Source](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2)

And Ladybird rightfully completely rejects it, if you enter an IPv6 without them:

[Screencast_20240803_195222.webm](https://github.com/user-attachments/assets/55bf3086-f49a-4947-ae2f-0db50d1359d8)

**Comment by circl-lastname** [comment]
Ladybird doesn't implement everything up to spec, a bit ago some basic IPv6 parsing was added, but not sure if it supports the `[]` notation. I'm asking if a pure IPv6 address with no port will work. Apologies as my home ISP does not provide IPv6 so I cannot check

**Comment by RubenKelevra** [comment]
> Ladybird doesn't implement _everything_ up to spec

Well, I thought that's one of the main goals of the project: To reimplement every single thing exactly to spec and complain if the spec does not work to fix the specs:

![Ladybird - Ladybird browser update (July 2024)  7sDL7LRkugk - 1280x720 - 1m50s](https://github.com/user-attachments/assets/56838f5c-feca-4871-9bd2-7955c10d8b20)


Sorry if I understood something wrong there.

> a bit ago some basic IPv6 parsing was added, but not sure if it supports the [] notation. I'm asking if a pure IPv6 address with no port will work. Apologies as my home ISP does not provide IPv6 so I cannot check myself

So to sum it up what is currently happening:

* Enter a IPv6 wrongly without square brackets: Will be completely discarded - as it should according the standard - as it's no valid host literal. It could be interpreted as search term, tho.
* Entering an IPv6 correctly, like `http://[ipv6]`, will lead to https://github.com/LadybirdBrowser/ladybird/issues/941 where it cannot reach the server for some odd reason.
* Entering an IPv6 correctly but with a port, like `http://[ipv6]:port` will lead to this error, as pasting it in will convert `[` and `]` to a Punycode, but after hitting enter it will be converted back to `[` and `]`.

So this bug is about a cosmetic bug while content is pasted into the address line, if there's an IPv6 with a port specified, it doesn't seem to be recognized correctly and interpreted as other part of the URL and converted to Punycode.

All the other issue regarding not reaching IPv6 servers is in https://github.com/LadybirdBrowser/ladybird/issues/941

**Comment by circl-lastname** [comment]
I never said it is not the goal of the Ladybird project, I just said it has not been reached yet, and I'm trying to further identify if these issues are related, I apologize

**Comment by circl-lastname** [comment]
I was unaware that the `[]` is the only valid notation for IPv6 URLs, sorry

**Comment by xlmnxp** [comment]
@RubenKelevra @circl-lastname I will look into this issue

**Comment by xlmnxp** [comment]
I discontinue working on this project, I will not contribute on this issue

**Comment by RubenKelevra** [comment]
I've checked it with 34261e54901 and it's fixed. Thanks!
