### ISSUE TITLE
Ladybird hangs when loading leboncoin.fr

### ISSUE THREAD

**Issue by warpdesign** [LadybirdBrowser/ladybird#968]
When attempting to load https://leboncoin.fr most of the page is displayed and then Ladybird hangs. Mouse scroll/clicks do not respond anymore (the mouse pointer shows the busy cursor on macOS). Logs does not show any crash, it just hangs.

**Comment by AtkinsSJ** [comment]
My system very quickly ran out of memory when I tried that page in Ladybird.

**Comment by warpdesign** [comment]
Interesting. Not sure how to reduce it.

**Comment by warpdesign** [comment]
Seems to be using lots of memory indeed: after a few seconds it goes from 30Mb to 104Gb (and it doesn't stop there):

![Capture d’écran 2024-09-09 à 09 57 00](https://github.com/user-attachments/assets/585cdad4-3052-4543-8c12-237df674d150)

Memory leak or something using too much memory in Ladybird's implementation?

**Comment by trflynn89** [comment]
The OOM issue is in our regex impl. The site has the following regex:
```
^\?((&?category=[0-9]+)?(&?shippable=1)?(&?ad_type=demand)?(&?page=[0-9]+)?(&?locations=(r|d)_[0-9]+)?)+$`
```

Executed on the string:
```
?category=54&shippable=1&baby_age=p,0,1,3
```

This regex spins forever and eats up memory.

**Comment by warpdesign** [comment]
Good catch!
