### ISSUE TITLE
LibHttp: HttpRequest::to_raw_request() improperly percent encodes "%" in URL path

### ISSUE THREAD

**Issue by alec3660** [LadybirdBrowser/ladybird#978]
`HttpRequest::to_raw_request()` uses `URL::PercentEncodeSet::EncodeURI` as the set to `percent_encode()` the URL path, which improperly percent encodes the "%" character, and breaks URLs which rely on this, e.g. Lainchan's programming board:

![lc-before](https://github.com/user-attachments/assets/8bc86f9b-6204-4665-8f54-d4d039b78d14)

where the request that is sent to the web server is: `GET /%25CE%25BB/index.html HTTP/1.1`

Changing the set to `URL::PercentEncodeSet::Path` appears to fix the problem:

![lc-after](https://github.com/user-attachments/assets/060cbbb3-724d-4f8c-b12b-ec4297fabccb)

There is a comment in the source file that explains the following:

`// NOTE: The percent_encode is so that e.g. spaces are properly encoded.`

I checked with `URL::PercentEncodeSet::Path` and spaces appear to be properly encoded when using this set.

Is anyone aware of any resources that currently rely on using `URL::PercentEncodeSet::EncodeURI` as the percent encode set for the URL path? If there are none, I can open up a pull request to resolve this particular issue.

**Comment by shannonbooth** [comment]
Yeah, that looked incorrect to me as well when I was looking at the other day, but the NOTE also made me leave as is and not investigate further. Is the problem fixed altogether by just removing the percent_encode alltogether? `url.serialize_path()` should give a percent encoded path anyhow.

**Comment by shannonbooth** [comment]
Ah, it was a derp of mine - it was previosuly decoded and then rencoded into encodeURI.
